'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const os = require('os')
const path = require('path')
const { marker, override, themeModalCss, patchAdminShellStability } = require('./patch-admin-shell-stability-v136')

test('sidebar control has one SVG source and disables both pseudo-elements', () => {
  const source = fs.readFileSync('tenant-setup-client.js', 'utf8')
  assert.match(source, /button\.ts-sidebar-toggle::before,button\.ts-sidebar-toggle::after\{[^}]*content:none!important/)
  assert.doesNotMatch(source, /button\.ts-sidebar-toggle::before\{width:10px/)
  assert.match(source, /button\.innerHTML = icon\(expectedIcon, 'ts-sidebar-chevron'\)/)
})

test('commercial header, current user and centered embedded settings are enforced', () => {
  const source = fs.readFileSync('commercial-admin-v101.js', 'utf8')
  assert.match(source, /\.admin-shell-header,.admin-app-shell \.admin-shell-header,body \.admin-app-shell \.admin-shell-header\.admin-shell-header\{display:block!important;visibility:visible!important;opacity:1!important\}/)
  assert.match(source, />\.admin-mobile-header\{display:none!important\}body \.admin-app-shell \.admin-shell-header\.admin-shell-header>\.admin-desktop-header\{display:flex!important\}/)
  assert.match(source, /data-ca-current-user/)
  assert.match(source, /data-ca-notification-button/)
  assert.match(source, /\/api\/lien-staff-notifications/)
  assert.match(source, /\/api\/admin\/billing\/status/)
  assert.match(source, /messageCount/)
  assert.match(source, /remainingTrialDays/)
  assert.match(source, /grid-template-columns:minmax\(0,1fr\)!important;justify-content:center!important/)
  assert.match(source, /data-ca-embedded-content/)
  assert.match(source, /\.ca-settings-embedded header\.admin-shell-header/)
  assert.match(source, /ADMIN_THEME_KEY = 'salon-lien:admin-theme'/)
  assert.match(source, /function enhanceAccountTheme\(\)/)
  assert.match(source, /data-ca-theme-option="dark"/)
  assert.match(source, /html\[data-ca-theme="dark"\]/)
  assert.match(source, /commercial-admin-theme-v145/)
  assert.match(source, /style\.textContent\.slice\(isolatedStart\)/)
  assert.match(source, /prepareStandaloneSettings\(root\)/)
  assert.match(source, /function normalizeSidebarControl\(\)/)
  assert.match(source, /button\.innerHTML = icon\(expected, 'ca-sidebar-chevron'\)/)
  assert.match(source, /body button\[aria-label="サイドバーを閉じる"\]/)
  assert.match(source, /function ensureHeaderActionShell\(actions, profile = null\)/)
  assert.match(source, /actionHosts\.forEach\(actions => ensureHeaderActionShell\(actions\)\)\s+const panels = ensureHeaderPanels\(\)\s+bindStoreMenuEvents\(\)\s+try \{\s+const profile = await getProfile\(\)/)
  assert.match(source, /if \(document\.readyState === 'loading'\) window\.addEventListener\('DOMContentLoaded', start/)
  assert.doesNotMatch(source, /window\.setTimeout\(boot, 250\)/)
})

test('tenant route enhancements start on the first animation frame', () => {
  const source = fs.readFileSync('tenant-setup-client.js', 'utf8')
  assert.match(source, /const startAfterHydration = \(\) => window\.requestAnimationFrame\(bootAfterHydration\)/)
  assert.doesNotMatch(source, /window\.setTimeout\(bootAfterHydration, 1800\)/)
})

test('shift time labels and vertical rules use the same 30 minute slot grid', () => {
  const source = fs.readFileSync('tenant-setup-client.js', 'utf8')
  assert.match(source, /--ts-shift-slots:18/)
  assert.match(source, /background-size:calc\(100% \/ var\(--ts-shift-slots\)\) 100%/)
  assert.match(source, /\.shift-lane\{[^}]*background-size:calc\(100% \/ var\(--ts-shift-slots\)\) 100%!important/)
  assert.match(source, /\.shift-lane>span\.pointer-events-none\.absolute\.inset-y-0\.border-l\{display:none!important\}/)
  assert.match(source, /setProperty\('--ts-shift-slots', String\(duration \/ 30\)\)/)
  assert.match(source, /\(\(index \* 2 \+ 1\) \/ slots\.length\) \* 100/)
  assert.match(source, /function alignShiftAppointments\(\)/)
  assert.match(source, /function alignShiftLaneGrid\(\)/)
  assert.match(source, /canvas\.dataset\.tsLaneGrid = `\$\{slots\}-slots`/)
  assert.match(source, /\(visibleStart - openMinutes\) \/ duration/)
  assert.match(source, /\(visibleEnd - visibleStart\) \/ duration/)
  assert.match(source, /setProperty\('left', `\$\{leftPercent\.toFixed\(6\)\}%`\)/)
  assert.match(source, /setProperty\('width', `calc\(\$\{widthPercent\.toFixed\(6\)\}% - 2px\)`\)/)
  assert.match(source, /alignShiftLaneGrid\(\)\n\s+alignShiftAppointments\(\)\n\s+normalizeShiftNowMarker\(\)/)
  assert.match(source, /currentMinutes - openMinutes\) \/ duration/)
})

test('build patch adds idempotent header and first-paint sidebar overrides', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lien-admin-shell-'))
  const cssDir = path.join(root, '.next', 'static', 'css')
  fs.mkdirSync(cssDir, { recursive: true })
  const file = path.join(cssDir, 'app.css')
  const manifest = path.join(root, '.next', 'build-manifest.json')
  fs.writeFileSync(file, 'x{}@media(min-width:1024px){body>div:first-child>div>header:first-child{display:none!important}}')
  fs.writeFileSync(manifest, JSON.stringify({ css: ['app.css'] }))
  patchAdminShellStability(root)
  patchAdminShellStability(root)
  const renamed = path.join(cssDir, `app.${marker}.css`)
  const output = fs.readFileSync(renamed, 'utf8')
  assert.equal(output.split(marker).length - 1, 1)
  assert.ok(output.includes(override))
  assert.match(output, /body header\.admin-shell-header/)
  assert.match(output, /visibility:visible!important/)
  assert.match(output, /button\[aria-label="サイドバーを閉じる"\]/)
  assert.match(output, /font-size:0!important/)
  assert.match(output, /admin-desktop-header>div:first-child\{display:grid!important;width:104px!important/)
  assert.match(output, /ca-header-store-mount:empty::before/)
  assert.match(output, /padding-left:52px!important/)
  assert.match(output, /header\.admin-shell-header:first-child>div\.admin-desktop-header\{padding-left:52px!important/)
  assert.match(output, /html\[data-ca-theme="dark"\]/)
  assert.ok(output.includes(themeModalCss))
  assert.match(output, /\.ca-settings-embedded \[data-ca-embedded-content\]/)
  assert.match(output, /\.ca-theme-options/)
  assert.equal(fs.existsSync(file), false)
  assert.match(fs.readFileSync(manifest, 'utf8'), new RegExp(`app\\.${marker}\\.css`))
})
