import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import {execFileSync} from 'node:child_process'
import {createRequire} from 'node:module'
const require=createRequire(path.resolve('../node_modules/playwright-core/package.json'))
const {chromium}=require('playwright-core')
const base='http://127.0.0.1:3188'
const config=JSON.parse(execFileSync('docker',['inspect','orimia-qa-v680-app'],{encoding:'utf8'}))[0]
assert.ok(config.Config.Env.includes('ORIMIA_ISOLATED_QA=v680'))
assert.ok(config.Config.Env.some(e=>e.includes('/orimia_qa_v680_20260926?')))
const tag=Date.now().toString(36), email=`qa680.${tag}@example.test`, login=`qa680_${tag}`, password='QaLocalOnly-v680!'
const phone='090'+String(Date.now()).slice(-8)
const mail=()=>execFileSync('docker',['exec','orimia-qa-v680-app','cat','/tmp/qa-mail.jsonl'],{encoding:'utf8'}).trim().split('\n').map(JSON.parse).filter(m=>m.To===email)
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'})
const checks=[]
const out='artifacts/three-app-qa-v680'
try {
  const context=await browser.newContext({viewport:{width:390,height:844},locale:'ja-JP',timezoneId:'Asia/Tokyo'})
  const page=await context.newPage()
  page.setDefaultTimeout(12000)
  const errors=[];page.on('pageerror',e=>{const error={url:page.url(),message:e.message};errors.push(error);console.error(JSON.stringify(error))})
  await page.goto(base+'/u/register')
  await page.locator('[name=email]').fill(email)
  await page.getByRole('button',{name:'登録用メールを送る',exact:true}).click()
  await page.getByText('登録用メールを送信しました。受信箱と迷惑メールをご確認ください。リンクは60分間有効です。',{exact:true}).waitFor()
  checks.push('registration email request and cooldown')
  const url=mail().at(-1).TextBody.match(/https?:\/\/[^\s]+/)[0]
  assert.equal(new URL(url).origin,base)
  await page.goto(url)
  await page.locator('[name=loginId]').waitFor({state:'visible'})
  await page.locator('[name=loginId]').fill('invalid.id')
  assert.equal(await page.locator('[name=loginId]').evaluate(e=>e.checkValidity()),false)
  await page.locator('form').evaluate(e=>{e.noValidate=true;e.requestSubmit()})
  await page.waitForURL(u=>u.searchParams.get('error')==='credentials')
  await page.getByRole('alert').filter({hasText:'ログインIDは半角英数字'}).waitFor()
  checks.push('invalid login ID rejected in browser and handled without server exception')
  for(const [name,value] of Object.entries({loginId:login,password,lastName:'検証',firstName:'花子',lastNameKana:'ケンショウ',firstNameKana:'ハナコ',phone,birthDate:'1990-01-01'}))await page.locator(`[name=${name}]`).fill(value)
  for(const select of await page.locator('select').all())await select.selectOption({index:1})
  const sms=page.waitForResponse(r=>r.url().includes('/phone-verification/request'))
  await page.getByRole('button',{name:'認証コードを送信',exact:true}).click()
  const smsData=await(await sms).json()
  assert.match(smsData.developmentCode,/^\d{6}$/)
  await page.getByPlaceholder('6桁のコード').fill(smsData.developmentCode)
  await page.getByRole('button',{name:'コードを確認',exact:true}).click()
  await page.getByText('電話番号を確認しました。このままプロフィール登録へ進めます。',{exact:true}).waitFor()
  await page.getByRole('button',{name:'登録する',exact:true}).click()
  await page.waitForURL(u=>u.pathname==='/u/login'&&u.searchParams.get('registered')==='1')
  checks.push('SMS verification and registration completion')
  await page.locator('[name=password]').fill(password)
  await page.getByRole('button',{name:'ログインする',exact:true}).click()
  await page.waitForURL(u=>u.pathname==='/u/home')
  await page.goto(base+'/u/profile#details')
  await page.locator('form[action="/api/customer/profile"] [name=lastName]').waitFor({state:'visible'})
  assert.equal(await page.locator('[name=lastName]').inputValue(),'検証')
  assert.equal(await page.locator('[name=firstNameKana]').inputValue(),'ハナコ')
  await page.locator('form[action="/api/customer/profile"] [name=nickname]').fill('QA会員')
  await page.locator('form[action="/api/customer/profile"] button[type=submit]').click()
  await page.waitForTimeout(700)
  await page.reload()
  await page.locator('[name=nickname]').waitFor({state:'visible'})
  assert.equal(await page.locator('[name=nickname]').inputValue(),'QA会員')
  checks.push('first login, structured names, profile edit persistence')
  await page.locator('form[action="/api/customer-auth/withdrawal/request"] button').click()
  await page.getByText('退会確認メールを送信しました。30分以内にメール内のリンクを開いてください。',{exact:true}).waitFor()
  const withdrawal=mail().findLast(m=>m.Subject.includes('退会')).TextBody.match(/https?:\/\/[^\s]+/)[0]
  await page.goto(withdrawal)
  await page.getByRole('button',{name:'退会を確定する',exact:true}).click()
  await page.getByText('退会が完了しました',{exact:true}).waitFor()
  checks.push('withdrawal request, confirmation email, confirmation and completion')
  await page.goto(base+'/u/login')
  await page.locator('[name=loginId]').fill(login)
  await page.locator('[name=password]').fill(password)
  await page.getByRole('button',{name:'ログインする',exact:true}).click()
  await page.waitForURL(u=>u.pathname==='/u/login'&&u.searchParams.get('error')==='credentials')
  await page.waitForTimeout(2000)
  checks.push('withdrawn account cannot log in')
  await page.screenshot({path:out+'/lifecycle-withdrawn-login.png'})
  fs.writeFileSync(out+'/lifecycle.json',JSON.stringify({passed:errors.length===0,checks,errors},null,2))
  assert.deepEqual(errors,[])
  console.log(JSON.stringify({passed:true,checks}))
} finally {await browser.close()}
