import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
const require=createRequire('/app/flam-export-v694/package.json'),Excel=require('exceljs'),{headers,prepare}=require('./export.cjs')
export async function verify({db,req,ok,a,b,staff,employee,base,month,makeOrder}){
 const run=(q,...p)=>db.$executeRawUnsafe(q,...p),get=(q='',cookie=a)=>ok('/api/dealer/erp/flam-preview?month='+month+q,cookie)
 const codes=[{id:'salon-a',code:'0000123'},{id:'salon-b',code:'0000456'}]
 assert.equal((await req('/api/dealer/erp/flam-preview?month='+month)).status,401)
 assert.equal((await get()).errors.length,1,'Missing external code blocks download')
 assert.equal((await req('/api/dealer/erp/flam-export.xlsx?month='+month,a)).status,422)
 assert.equal((await req('/api/dealer/erp/flam-customer-codes',staff,{customers:codes})).status,403)
 assert.equal((await req('/api/dealer/erp/flam-customer-codes',a,{customers:codes},{Origin:'https://evil.example'})).status,403)
 assert.equal((await req('/api/dealer/erp/flam-customer-codes',b,{customers:codes})).status,404)
 for(const code of ['1'.repeat(16),'あいう','a\nb'])assert.equal((await req('/api/dealer/erp/flam-customer-codes',a,{customers:[{id:'salon-a',code}]})).status,400)
 await ok('/api/dealer/erp/flam-customer-codes',a,{customers:codes})
 const first=await get();assert.deepEqual(first.errors,[])
 assert.equal(first.summary.actualYen,(await ok('/api/dealer/sales?month='+month,a)).summary.actualYen)
 assert.equal((await get('',b)).summary.lines,0,'Other dealers cannot see source data')
 assert.equal((await get('&salon=salon-b',staff)).summary.lines,0,'Staff scope applies before filters')
 assert.equal((await get('&member=forbidden',staff)).summary.actualYen,(await get('',staff)).summary.actualYen,'Forged member cannot expand scope')
 assert.equal((await get('&branch=missing')).summary.lines,0)
 assert.equal((await get('&closing=1')).summary.lines,0)
 assert.equal((await req('/api/dealer/erp/flam-preview?month='+month+'&closing=99',a)).status,400)
 assert.equal((await req('/api/dealer/erp/flam-export.xlsx?month='+month+'&token=wrong',a)).status,409)
 const beforeOrders=await db.$queryRawUnsafe('SELECT id,status,"subtotalYen" FROM "WholesaleOrder" ORDER BY id')
 const response=await fetch(base+'/api/dealer/erp/flam-export.xlsx?month='+month+'&token='+first.token,{headers:{Cookie:a}})
 assert.equal(response.status,200);assert.match(response.headers.get('content-type'),/spreadsheetml/);assert.match(response.headers.get('cache-control'),/no-store/)
 const book=new Excel.Workbook();await book.xlsx.load(Buffer.from(await response.arrayBuffer()))
 const sheet=book.getWorksheet('Sheet1');assert.equal(book.worksheets.length,1);assert.deepEqual(sheet.getRow(1).values.slice(1),headers)
 assert.equal(sheet.columnCount,105);assert.equal(sheet.rowCount,first.summary.lines+1)
 let total=0,negative=0
 const unused=headers.map((h,i)=>h==='未使用'?i+1:null).filter(Boolean)
 sheet.eachRow((row,n)=>{if(n===1)return;total+=row.getCell(55).value;if(row.getCell(48).value<0){negative++;assert.equal(row.getCell(38).value,3);assert.equal(row.getCell(3).value,312)}
  assert.equal(row.getCell(14).value,'0000123');assert.ok(row.getCell(2).value instanceof Date);assert.ok(/^\d{8}$/.test(row.getCell(1).value));assert.equal(row.getCell(47).value*row.getCell(48).value,row.getCell(55).value)
  assert.equal(row.getCell(40).value,null);assert.equal(row.getCell(6).value,null);assert.equal(row.getCell(28).value,null);for(const col of unused)assert.equal(row.getCell(col).value,null)
 })
 assert.equal(total,first.summary.actualYen);assert.ok(negative>0,'Actual return entries included')
 assert.deepEqual(await db.$queryRawUnsafe('SELECT id,status,"subtotalYen" FROM "WholesaleOrder" ORDER BY id'),beforeOrders)
 await ok('/api/dealer/erp/flam-customer-codes',a,{customers:[{id:'salon-a',code:'0000124'}]})
 assert.equal((await req('/api/dealer/erp/flam-export.xlsx?month='+month+'&token='+first.token,a)).status,409,'Changed mapping invalidates preview')
 await ok('/api/dealer/erp/flam-customer-codes',a,{customers:codes})
 await makeOrder('flam-legacy','salon-b',2)
 await run('UPDATE "WholesaleOrder" SET status=\'DELIVERED\',"deliveredAt"=NOW() WHERE id=\'flam-legacy\'')
 await run('UPDATE "WholesaleOrderLine" SET "deliveredQuantity"=0 WHERE "orderId"=\'flam-legacy\'')
 assert.equal((await get('&salon=salon-b')).summary.actualYen,1600,'Legacy full delivery represented once')
 const current=await get();assert.equal(current.summary.actualYen,first.summary.actualYen+1600)
 assert.equal((await get('&productCodes=1')).errors.length,0)
 const assigned=(await db.$queryRawUnsafe('SELECT "branchId" FROM "DealerSalesMember" WHERE id=$1',employee.id))[0]
 assert.equal((await get('&branch='+assigned.branchId)).summary.actualYen,first.summary.actualYen)
 assert.equal((await get('&member='+employee.id)).summary.actualYen,first.summary.actualYen)
 assert.equal((await get('&closing=20')).summary.actualYen,first.summary.actualYen)
 assert.equal((await get('&closing=31')).summary.actualYen,1600)
 const delivered=(await db.$queryRawUnsafe('SELECT "deliveredAt" FROM "WholesaleOrder" WHERE id=\'flam-legacy\''))[0].deliveredAt
 const start=new Date(month+'-01T00:00:00+09:00')
 for(const [at,expected] of [[new Date(start.getTime()-1),0],[start,1600]]){
  await run('UPDATE "WholesaleOrder" SET "deliveredAt"=$1 WHERE id=\'flam-legacy\'',at)
  assert.equal((await get('&salon=salon-b')).summary.actualYen,expected,'SQL uses JST month boundary')
 }
 await run('UPDATE "WholesaleOrder" SET "deliveredAt"=$1 WHERE id=\'flam-legacy\'',delivered)
 const charge=(await db.$queryRawUnsafe('SELECT id,quantity,"unitPrice","productName","productCode" FROM "DealerErpCharge" WHERE quantity>0 LIMIT 1'))[0]
 await run('UPDATE "DealerErpCharge" SET quantity=1,"unitPrice"=650,"productName"=\'送料\',"productCode"=\'\' WHERE id=$1',charge.id)
 const freight=await get()
 assert.equal(freight.summary.actualYen,current.summary.actualYen-charge.quantity*charge.unitPrice+650)
 assert.equal((await req('/api/dealer/erp/flam-export.xlsx?month='+month+'&token='+current.token,a)).status,409,'Source change invalidates preview')
 const freightFile=await fetch(base+'/api/dealer/erp/flam-export.xlsx?month='+month+'&token='+freight.token,{headers:{Cookie:a}})
 const freightBook=new Excel.Workbook();await freightBook.xlsx.load(Buffer.from(await freightFile.arrayBuffer()))
 assert.ok(freightBook.getWorksheet('Sheet1').getRows(2,freight.summary.lines).some(r=>r.getCell(43).value==='送料'&&r.getCell(55).value===650),'Freight exports as a normal net line')
 await run('UPDATE "DealerErpCharge" SET quantity=$2,"unitPrice"=$3,"productName"=$4,"productCode"=$5 WHERE id=$1',charge.id,charge.quantity,charge.unitPrice,charge.productName,charge.productCode)
 const source={sourceId:'unit',orderId:'unit',orderNo:'PO-TEST',organizationId:'salon-a',salonName:'A',customerCode:'00001',productName:'=HYPERLINK("evil")',productCode:'001234',quantity:1,unitPrice:125,amount:125,taxRate:10,at:'2026-09-30T15:00:00.000Z'}
 const pure=prepare([source],true);assert.equal(pure.rows[0][1],'2026-10-01');assert.equal(pure.rows[0][39],'001234');assert.equal(pure.rows[0][42],source.productName)
 assert.equal(pure.rows[0][55],null,'Tax follows FLAM customer settings, not an invented amount')
 assert.equal(prepare([{...source,productName:'髪'.repeat(150)}],false).rows[0][43].length,50)
 assert.ok(prepare([{...source,amount:126}],false).errors.length)
 assert.ok(prepare([{...source,taxRate:7}],false).errors.length)
 assert.ok(prepare([{...source,productCode:'長い商品コード'}],true).errors.length)
 assert.equal(prepare([{...source,productCode:'長い商品コード'}],false).errors.length,0)
 assert.equal(prepare(Array.from({length:5001},(_,i)=>({...source,sourceId:String(i)})),false).summary.documents,2)
 console.log('v694 integration PASS: XLSX 105 columns, unused blanks, codes/leading zero, returns/legacy/partial sales, all filters and staff scopes, CSRF/tenant isolation, snapshot reconciliation, stale download, no order mutation, JST and 5000-line document split')
}
