import assert from 'node:assert/strict'
export async function verify({db,req,ok,a,b,staff,employee,branch}){
 const run=(sql,...args)=>db.$executeRawUnsafe(sql,...args)
 const members=await db.$queryRawUnsafe('SELECT * FROM "DealerSalesMember"')
 const owner=members.find(m=>m.dealerId==='dealer-a'&&m.id!==employee.id),foreign=members.find(m=>m.dealerId==='dealer-b')
 const date='2028-02-29',route='/api/dealer/erp/calendar-day?date='+date
 const fetchDay=(cookie=a,suffix='')=>ok(route+suffix,cookie)
 assert.equal((await req(route)).status,401)
 for(const d of ['2026-02-29','2028-02-30','2028-2-29','bad'])assert.equal((await req('/api/dealer/erp/calendar-day?date='+d,a)).status,400)
 assert.equal((await req('/api/admin/wholesale/erp/calendar-day?dealer=dealer-a&date='+date,'',undefined,{'x-fixture-salon':'salon-a'})).status,404)
 const addOrder=async(id,total,member=employee.id,ordered='2028-02-29T10:00:00+09:00',business=null,status='ORDERED',dealer='dealer-a')=>run('INSERT INTO "WholesaleOrder" (id,"orderNo","dealerId","organizationId","orderedByName","subtotalYen","taxYen","totalYen","salesMemberId","salesBranchId","orderedAt","businessDate",status) VALUES ($1,$1,$2,\'salon-a\',\'fixture\',$3,0,$3,$4,$5,$6,$7::date,$8)',id,dealer,total,member,branch.id,new Date(ordered),business,status)
 await addOrder('day-own',6600)
 await addOrder('day-other',4400,owner.id)
 await run('UPDATE "WholesaleOrder" SET "salesMemberId"=$1 WHERE id=\'day-other\'',owner.id)
 await addOrder('day-cutoff-next',2200,employee.id,'2028-02-29T12:00:00+09:00','2028-03-01')
 await addOrder('day-cutoff-prior',1100,employee.id,'2028-02-28T12:00:00+09:00',date)
 await addOrder('day-cancelled',9900,employee.id,undefined,null,'CANCELLED')
 await addOrder('day-jst-end',1200,employee.id,'2028-02-29T14:59:59Z')
 await addOrder('day-next-midnight',8800,employee.id,'2028-02-29T15:00:00Z')
 await addOrder('day-foreign',555,foreign.id,undefined,null,'ORDERED','dealer-b')
 const addActivity=async(id,member,visibility='PRIVATE',starts=date+'T09:00:00+09:00',ends=date+'T10:00:00+09:00',branchId=branch.id,status='PLANNED',dealer='dealer-a')=>run('INSERT INTO "DealerErpActivity" (id,"dealerId","memberId","branchId","organizationId",kind,title,"startsAt","endsAt",visibility,status,note) VALUES ($1,$2,$3,$4,\'salon-a\',\'VISIT\',$5,$6,$7,$8,$9,$10)',id,dealer,member,branchId,'訪問 '+id,new Date(starts),new Date(ends),visibility,status,'サロンへ商品案内 <script>window.dayXss=1</script>')
 await addActivity('own-visit',employee.id)
 await addActivity('owner-private',owner.id)
 await addActivity('branch-shared',owner.id,'BRANCH')
 await addActivity('other-branch',owner.id,'BRANCH',undefined,undefined,null)
 await addActivity('dealer-shared',owner.id,'DEALER')
 await addActivity('cancelled-visit',employee.id,'PRIVATE',undefined,undefined,branch.id,'CANCELLED')
 await addActivity('overnight',employee.id,'PRIVATE','2028-02-28T23:30:00+09:00',date+'T00:30:00+09:00')
 await addActivity('ends-midnight',employee.id,'PRIVATE','2028-02-28T23:00:00+09:00',date+'T00:00:00+09:00')
 await addActivity('starts-next-midnight',employee.id,'PRIVATE','2028-03-01T00:00:00+09:00','2028-03-01T01:00:00+09:00')
 await addActivity('other-dealer',foreign.id,'DEALER',undefined,undefined,null,'PLANNED','dealer-b')
 let detail=await fetchDay()
 assert.equal(detail.orders.total,4);assert.equal(detail.orders.forecastYen,13300)
 assert.equal(detail.activities.total,7);assert.equal(detail.activities.activeCount,6)
 assert.ok(detail.orders.rows.every(r=>r.member));assert.ok(detail.activities.rows.every(r=>r.salon==='テストサロン A'))
 assert.ok(!detail.activities.rows.some(r=>['other-dealer','ends-midnight','starts-next-midnight'].includes(r.id)))
 const restricted=await fetchDay(staff)
 assert.equal(restricted.orders.total,3);assert.equal(restricted.orders.forecastYen,8900)
 assert.equal(restricted.activities.total,5);assert.equal(restricted.activities.activeCount,4)
 assert.ok(!restricted.activities.rows.some(r=>['owner-private','other-branch','other-dealer'].includes(r.id)))
 assert.equal((await fetchDay(b)).orders.total,1);assert.equal((await fetchDay(b)).activities.total,1)
 for(const [cookie,value] of [[a,13300],[staff,8900]]){
  const calendar=(await ok('/api/dealer/calendar?month=2028-02',cookie)).calendar
  assert.equal(calendar.days.find(d=>d.date===date).forecastYen,value)
 }
 const empty=await ok('/api/dealer/erp/calendar-day?date=2028-03-05',a)
 assert.equal(empty.orders.total,0);assert.equal(empty.activities.total,0)
 assert.equal((await req('/api/dealer/calendar/targets',staff,{monthKey:'2028-02',salesTargetYen:1,newAcquisitionCount:1})).status,403)
 // Separate busy day verifies both lists paginate without silently dropping entries.
 for(let i=0;i<35;i++){
  await addOrder('many-order-'+i,100,employee.id,'2028-03-06T10:00:00+09:00')
  await addActivity('many-activity-'+i,employee.id,'PRIVATE','2028-03-06T09:00:00+09:00','2028-03-06T10:00:00+09:00')
 }
 const busyRoute='/api/dealer/erp/calendar-day?date=2028-03-06'
 const first=await ok(busyRoute,a),second=await ok(busyRoute+'&orderPage=2&activityPage=2',a)
 assert.equal(first.orders.rows.length,30);assert.equal(second.orders.rows.length,5);assert.equal(second.orders.forecastYen,3500)
 assert.equal(first.activities.rows.length,30);assert.equal(second.activities.rows.length,5)
 assert.equal(new Set([...first.orders.rows,...second.orders.rows].map(r=>r.id)).size,35)
 assert.equal(new Set([...first.activities.rows,...second.activities.rows].map(r=>r.id)).size,35)
 assert.equal((await ok(busyRoute+'&orderPage=9999',a)).orders.page,2)
 const html=await req('/dealer/calendar?month=2028-02',a)
 assert.match(html.content,/dealer-calendar-v696.js/);assert.match(html.content,/dealer-calendar-day-v696.css/)
 console.log('v696 integration PASS: day totals, cutoff dates, JST midnight/leap day, owner/staff/tenant/privacy scopes, pagination, cancelled and empty states')
}
