'use strict'
const fs=require('node:fs'),path=require('node:path')
const read=f=>fs.readFileSync('/app/'+f,'utf8'),write=(f,s)=>fs.writeFileSync('/app/'+f,s),local=f=>fs.readFileSync(path.join(__dirname,f),'utf8')
function replace(s,a,b){if(s.split(a).length!==2)throw Error('Patch anchor: '+a.slice(0,100));return s.replace(a,()=>b)}
write('dealer-calendar-day-v696.cjs',local('day.cjs'))
write('public/dealer-calendar-day-v696.css',local('day.css'))
let erp=read('dealer-erp-v678.js')
erp=replace(erp,'  const getters = {','  const getters = { \'calendar-day\': require(\'./dealer-calendar-day-v696.cjs\').createCalendarDay(db),')
write('dealer-erp-v678.js',erp)
let service=read('wholesale-ordering-v543.js')
const start=service.indexOf('  async function dealerCalendarPayload('),end=service.indexOf('  async function saveDealerCalendarPlan(',start)
if(start<0||end<0)throw Error('Calendar scope anchor')
let calendar=service.slice(start,end)
calendar=replace(calendar,`            AND o."status"<>'CANCELLED'`,`            AND o."status"<>'CANCELLED'
            AND ($4::text IS NULL OR o."salesMemberId"=$4)`)
calendar=replace(calendar,'        range.endUtc,','        range.endUtc,\n        session.role === \'ADMIN\' ? null : session.memberId,')
write('wholesale-ordering-v543.js',service.slice(0,start)+calendar+service.slice(end))
let client=read('public/dealer-catalog-v695.js')
client=replace(client,'  function dealerCalendarGrid(calendar) {',local('client.js')+'\n  function dealerCalendarGrid(calendar) {')
client=replace(client,`cells.push('<article class="' + classes.join(' ')`,`cells.push('<button type="button" data-calendar-date="' + dayKey + '" aria-haspopup="dialog" class="' + classes.join(' ')`)
client=replace(client,`+ detail + '</article>')`,`+ detail + '</button>')`)
client=replace(client,'wo-calendar-no-orders-v658">予定なし','wo-calendar-no-orders-v658">受注なし')
client=replace(client,'受注した伝票を注文日ごとに集計しています。キャンセル済みの注文は見込み額に含みません。','締め切り時刻に基づく発注日ごとの売上見込み（税込）')
client=replace(client,'role="grid" aria-label="','role="group" aria-label="')
client=client.replaceAll('role="columnheader"','')
write('public/dealer-calendar-v696.js',client)
let workspace=read('dealer-workspace-v688.js')
workspace=replace(workspace,"  const client = view==='orders'", "  const client = view==='calendar' ? '/dealer-calendar-v696.js?v=696-1' : view==='orders'")
workspace=replace(workspace,"  const tabs = active.pages.length>1", "  if (view==='calendar') head=head.replace('</head>','<link rel=\"stylesheet\" href=\"/dealer-calendar-day-v696.css?v=696-1\"></head>')\n  const tabs = active.pages.length>1")
write('dealer-workspace-v688.js',workspace)
write('server.js',replace(read('server.js'),"res.setHeader('X-Lien-Dealer-Cascading-Filters','v695')","res.setHeader('X-Lien-Dealer-Cascading-Filters','v695')\n   if (url.pathname === '/api/health/ready') res.setHeader('X-Lien-Dealer-Calendar-Day','v696')"))
console.log('dealer-calendar-day-v696 applied')
