import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import fs from 'node:fs'
export async function verify({db,service,req,ok,a,b,staff,wh}){
 const sql=(q,...p)=>db.$queryRawUnsafe(q,...p),exec=(q,...p)=>db.$executeRawUnsafe(q,...p),sh={'x-fixture-salon':'1'}
 const act=(name,c,p,key=crypto.randomUUID())=>ok('/api/dealer/erp/'+name,c,{...p,key})
 const get=(name,c=a)=>ok('/api/dealer/erp/'+name,c)
 const denied=async(name,c,p,status=403)=>assert.equal((await req('/api/dealer/erp/'+name,c,{...p,key:crypto.randomUUID()})).status,status,name)
 await denied('supplier-save',staff,{name:'拒否',code:'NO'})
 const supplier=await act('supplier-save',a,{name:'メーカー仕入先A',code:'SUP-A'})
 const supplier2=await act('supplier-save',a,{name:'メーカー仕入先B',code:'SUP-B'})
 await denied('supplier-assign',b,{productId:'product-a',supplierId:supplier.id},404)
 await denied('supplier-assign',staff,{productId:'product-a',supplierId:supplier.id})
 await act('supplier-assign',a,{productId:'product-a',supplierId:supplier.id,supplierProductCode:'SUP-SKU-A',manufacturerProductCode:'M-SKU-A',unitCost:400})
 await act('supplier-assign',a,{productId:'product-a',supplierId:supplier2.id,supplierProductCode:'SUP2-SKU-A',unitCost:450})
 assert.equal((await sql('SELECT COUNT(*)::int n FROM "DealerProductSupplier" WHERE "productId"=\'product-a\' AND "isPrimary"'))[0].n,1)
 const payload={dealerId:'dealer-a',lines:[{dealerProductId:'product-a',quantity:2}],key:crypto.randomUUID()}
 const order=(await ok('/api/admin/wholesale/orders','',payload,sh)).order
 await denied('procurement-generate',staff,{version:'none'})
 const accepted=await act('order-accept',a,{orderId:order.id});assert.equal(accepted.status,'ACCEPTED')
 assert.ok(!(await get('procurement-preview')).rows.some(r=>r.orderId===order.id),'No procurement before cutoff')
 const before=await ok('/api/admin/wholesale/erp/order-amendment?id='+order.id+'&dealer=dealer-a','',undefined,sh)
 await ok('/api/admin/wholesale/erp/order-amend?dealer=dealer-a','',{orderId:order.id,version:before.version,lines:[{lineId:before.lines[0].id,quantity:3}],key:crypto.randomUUID()},sh)
 await exec('UPDATE "WholesaleOrderAmendment" SET "cutoffAt"=clock_timestamp()-interval \'1 minute\' WHERE "orderId"=$1',order.id)
 await exec('UPDATE "WholesaleOrder" SET "consolidationClosesAt"=clock_timestamp()-interval \'1 minute\' WHERE id=$1',order.id)
 await denied('order-amend',a,{orderId:order.id,version:before.version,lines:[{lineId:before.lines[0].id,quantity:1}]},409)
 let p=await get('procurement-preview?order='+order.id);assert.equal(p.rows[0].quantity,3);assert.equal(p.rows[0].supplierId,supplier2.id)
 const stale=p.version
 await act('supplier-assign',a,{productId:'product-a',supplierId:supplier.id,supplierProductCode:'SUP-SKU-A',manufacturerProductCode:'M-SKU-A',unitCost:400})
 await denied('procurement-generate',a,{order:order.id,version:stale},409)
 p=await get('procurement-preview?order='+order.id)
 const key=crypto.randomUUID(),generated=await act('procurement-generate',a,{order:order.id,version:p.version},key)
 assert.deepEqual(await act('procurement-generate',a,{order:order.id,version:p.version},key),generated)
 assert.equal(generated.purchases.length,1)
 const purchaseId=generated.purchases[0].id
 assert.equal((await get('procurement-preview?order='+order.id)).rows.length,0,'No duplicate upstream order')
 await denied('procurement-submit',a,{purchaseId,confirmed:true},409)
 assert.equal((await req('/api/dealer/flow/purchase.csv?id='+purchaseId,b)).status,404)
 const csv=await req('/api/dealer/flow/purchase.csv?id='+purchaseId,a)
 assert.equal(csv.status,200);assert.match(csv.content,/M-SKU-A/);assert.match(csv.content,/SUP-SKU-A/);assert.match(csv.content,/"3"/)
 const member=(await get('options',staff)).viewer.memberId
 await act('procurement-permission',a,{memberId:member,canProcure:true})
 await act('procurement-submit',staff,{purchaseId,confirmed:true})
 assert.equal((await get('order?id='+order.id)).order.procurementStatus,'ORDERED')
 await denied('procurement-submit',a,{purchaseId,confirmed:true},409)
 await denied('receive',a,{purchaseId,cancel:true},409)
 let purchase=(await get('purchases',staff)).rows.find(p=>p.id===purchaseId)
 await act('receive',staff,{purchaseId,lineId:purchase.lines[0].id,locationId:wh.locationId,quantity:3})
 await denied('stock-minimum',staff,{stockId:'any',minimum:3,version:0})
 await denied('salon-issue',staff,{name:'denied'})
 await act('reserve',staff,{orderId:order.id,lineId:before.lines[0].id,locationId:wh.locationId,quantity:3})
 const shipment=await act('ship',staff,{orderId:order.id})
 await act('deliver',staff,{shipmentId:shipment.id})
 assert.equal((await get('order?id='+order.id)).order.status,'DELIVERED')
 await act('discount-visibility',a,{organizationId:'salon-a',showDiscountRate:false})
 const bootstrap=await ok('/api/admin/wholesale/bootstrap','',undefined,sh)
 assert.ok(bootstrap.catalogProducts.length)
 for(const product of bootstrap.catalogProducts){assert.equal(product.discountRate,undefined);assert.equal(product.listPrice,undefined);assert.equal(product.unitPrice,800)}
 const amendment=await ok('/api/admin/wholesale/erp/order-amendment?id='+order.id+'&dealer=dealer-a','',undefined,sh)
 assert.equal(amendment.lines[0].discountRate,undefined);assert.equal(amendment.lines[0].listPrice,undefined)
 const day=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date())
 const invoice=await act('invoice',a,{organizationId:'salon-a',closingDate:day,dueDate:day})
 const doc=await req('/dealer/erp/invoice/'+invoice.id,a)
 assert.equal(doc.status,200);assert.match(doc.content,/販売単価/);assert.doesNotMatch(doc.content,/定価|値引|discountRate/)
 const delivery=await req('/dealer/flow/delivery/'+order.id,a)
 assert.equal(delivery.status,200);assert.match(delivery.content,/販売単価/);assert.doesNotMatch(delivery.content,/定価|値引/)
 assert.equal((await req('/dealer/flow/delivery/'+order.id,b)).status,404)
 const detail=await ok('/api/dealer/flow/salon?id=salon-a',a)
 assert.ok(detail.orders.some(o=>o.id===order.id));assert.ok(detail.invoices.some(i=>i.id===invoice.id))
 await act('procurement-permission',a,{memberId:member,canProcure:false})
 const month=day.slice(0,7)
 const analysis=await get('period-sales?month='+month)
 assert.equal(analysis.summary.actualYen,(await ok('/api/dealer/sales?month='+month,a)).summary.actualYen)
 assert.equal((await get('period-sales?month='+month,b)).summary.actualYen,0)
 const personal=await get('period-sales?month='+month,staff)
 const personalForced=await get('period-sales?month='+month+'&member=invalid',staff)
 assert.equal(personalForced.summary.actualYen,personal.summary.actualYen,'Cannot override assigned-member scope')
 const mreport=await get('manufacturer-sales?month='+month)
 assert.ok(mreport.rows.some(r=>r.productId==='product-a'&&r.organizationId==='salon-a'))
 assert.ok((await get('manufacturer-sales?month='+month,staff)).rows.every(r=>r.organizationId==='salon-a'))
 assert.equal((await get('manufacturer-sales?month='+month+'&manufacturer=不存在')).rows.length,0)
 assert.match((await req('/api/dealer/flow/manufacturer.csv?month='+month,a)).content,/売上金額/)
 const stockReport=await get('manufacturer-stock'),stock=stockReport.rows[0]
 await act('stock-minimum',a,{stockId:stock.id,minimum:7,version:stock.version})
 assert.equal((await get('manufacturer-stock')).rows.find(r=>r.id===stock.id).minimum,7)
 await denied('stock-minimum',a,{stockId:stock.id,minimum:8,version:stock.version},409)
 await denied('stock-minimum',b,{stockId:stock.id,minimum:8,version:stock.version},404)
 for(const [id,maker,supplierId] of [['split-1','MakerA',supplier.id],['split-2','MakerB',supplier.id],['split-3','MakerA',supplier2.id]]){
  await exec('INSERT INTO "WholesaleDealerProduct" (id,"dealerId","manufacturerName",name,category,"productCode","wholesalePrice") VALUES ($1,\'dealer-a\',$2,$1,\'TEST\',$1,1000)',id,maker)
  await act('supplier-assign',a,{productId:id,supplierId})
 }
 await exec('INSERT INTO "WholesaleOrder" (id,"orderNo","dealerId","organizationId","orderedByName") VALUES (\'split-order\',\'SPLIT-ORDER\',\'dealer-a\',\'salon-a\',\'test\')')
 for(const id of ['split-1','split-2','split-3'])await exec('INSERT INTO "WholesaleOrderLine" (id,"orderId","dealerProductId","manufacturerName","productName","productCode","unitPrice","listPrice",quantity,"deliveredQuantity","lineTotal") SELECT id,\'split-order\',id,"manufacturerName",name,"productCode",1000,1000,1,1,1000 FROM "WholesaleDealerProduct" WHERE id=$1',id)
 await act('order-accept',a,{orderId:'split-order'})
 await exec('UPDATE "WholesaleOrderAmendment" SET "cutoffAt"=NOW()-INTERVAL \'1 minute\' WHERE "orderId"=\'split-order\'')
 await exec('UPDATE "WholesaleOrder" SET "consolidationClosesAt"=NOW()-INTERVAL \'1 minute\' WHERE id=\'split-order\'')
 const split=await get('procurement-preview?order=split-order')
 const grouped=await act('procurement-generate',a,{order:'split-order',version:split.version})
 assert.equal(grouped.purchases.length,3,'Group by both supplier AND manufacturer')
 // Extend only the isolated authentication fixture with fields owned by the core schema.
 await exec('ALTER TABLE "Organization" ADD COLUMN IF NOT EXISTS slug TEXT, ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP DEFAULT NOW(), ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP DEFAULT NOW()')
 await exec('ALTER TABLE "AppUser" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP DEFAULT NOW(), ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP DEFAULT NOW()')
 await exec('CREATE TABLE IF NOT EXISTS "OrganizationStoreProfile" ("organizationId" TEXT PRIMARY KEY,"ownerName" TEXT,phone TEXT,"orimiaPublished" BOOLEAN)')
 await exec('ALTER TABLE "OrganizationStoreProfile" ADD COLUMN IF NOT EXISTS "ownerName" TEXT, ADD COLUMN IF NOT EXISTS "orimiaPublished" BOOLEAN')
 const issued=await act('salon-issue',a,{name:'LimitedSalon',contact:'Owner',email:'limited@example.invalid',phone:'000-0000-0000',loginId:'limited-test',password:'FixtureLimited-698!',memberId:member})
 const account=(await sql('SELECT * FROM "AppUser" WHERE "organizationId"=$1',issued.id))[0]
 assert.equal(account.orderOnlyPasswordChangeRequired,true)
 assert.equal((await sql('SELECT "serviceMode" FROM "Organization" WHERE id=$1',issued.id))[0].serviceMode,'ORDER_ONLY')
 const lh={'x-fixture-salon':'1','x-fixture-org':issued.id,'x-fixture-user':account.id}
 assert.equal((await req('/api/admin/wholesale/bootstrap','',undefined,lh)).status,428)
 await ok('/api/admin/ordering/password','',{currentPassword:'FixtureLimited-698!',password:'ChangedLimited-698!'},lh)
 for(const url of ['/api/admin/customers','/api/admin/settings','/api/admin/wholesale/inventory','/api/admin/wholesale/erp/chat-partners?dealer=dealer-a'])assert.equal((await req(url,'',undefined,lh)).status,403,url)
 assert.equal((await req('/admin/customers','',{},lh)).status,403,'Block Next Server Actions')
 assert.equal((await req('/admin/ordering/documents','',undefined,lh)).status,200)
 assert.equal((await req('/admin/ordering/invoice/'+invoice.id,'',undefined,lh)).status,404,'Cross-salon document denied')
 assert.equal((await req('/admin/ordering/delivery/'+order.id,'',undefined,lh)).status,404,'Cross-salon delivery denied')
 assert.equal((await ok('/api/admin/wholesale/bootstrap','',undefined,lh)).catalogProducts.length,0)
 await db.$transaction(async tx=>{for(const statement of fs.readFileSync('/app/dealer-order-flow-v698/migration.sql','utf8').split(';').filter(s=>s.trim()))await tx.$executeRawUnsafe(statement)})
 assert.equal((await sql('SELECT COUNT(*)::int n FROM "DealerErpPurchaseSource" WHERE "orderLineId"=$1',before.lines[0].id))[0].n,1,'Migration replay preserves source rows')
 console.log('PASS v698: supplier switching, permissions, cutoff/edit synchronization, CSV snapshots, idempotency, warehouse procurement, receive/deliver/invoice, hidden rates')
 console.log('PASS v698 Phase 2/3: target stock roles/versioning, manufacturer monthly CSV, period/member/tenant scope, multi-supplier grouping, restricted salon issuance/password/deny-by-default, migration replay')
}
