version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 009293460979.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - docker build -f Dockerfile.release-40 -t salon-de-lien-staging-app:temporary-sms-referral-off-cache-fix-20260813-48 .
      - docker tag salon-de-lien-staging-app:temporary-sms-referral-off-cache-fix-20260813-48 009293460979.dkr.ecr.ap-northeast-1.amazonaws.com/salon-de-lien-staging-app:temporary-sms-referral-off-cache-fix-20260813-48
  post_build:
    commands:
      - docker push 009293460979.dkr.ecr.ap-northeast-1.amazonaws.com/salon-de-lien-staging-app:temporary-sms-referral-off-cache-fix-20260813-48
      - printf '{"image":"009293460979.dkr.ecr.ap-northeast-1.amazonaws.com/salon-de-lien-staging-app:temporary-sms-referral-off-cache-fix-20260813-48"}' > image.json
artifacts:
  files:
    - image.json
