version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 009293460979.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - docker build -f Dockerfile.customer-interactions -t salon-de-lien-staging-app:customer-interactions-20260813-30 .
      - docker tag salon-de-lien-staging-app:customer-interactions-20260813-30 009293460979.dkr.ecr.ap-northeast-1.amazonaws.com/salon-de-lien-staging-app:customer-interactions-20260813-30
  post_build:
    commands:
      - docker push 009293460979.dkr.ecr.ap-northeast-1.amazonaws.com/salon-de-lien-staging-app:customer-interactions-20260813-30
