import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import {createRequire} from 'node:module'
const require=createRequire('/app/package.json'),{period,totals}=require('/app/order-consolidation-v692')
export async function verify({db,req,ok,a,b,staff,wh}){
 const sql=(q,...p)=>db.$queryRawUnsafe(q,...p),exec=(q,...p)=>db.$executeRawUnsafe(q,...p),sh={'x-fixture-salon':'1'}
 const act=(name,c,p)=>ok('/api/dealer/erp/'+name,c,{...p,key:crypto.randomUUID()})
 const get=(name,c=a)=>ok('/api/dealer/erp/'+name,c)
 const cart=quantity=>({dealerId:'dealer-a',lines:[{dealerProductId:'product-a',quantity}],key:crypto.randomUUID()})
 const submit=p=>ok('/api/admin/wholesale/orders','',p,sh),quote=p=>ok('/api/admin/wholesale/order-quote','',p,sh)
 assert.equal(period('2026-09-28T01:59:59.999Z',660).businessDate,'2026-09-28')
 assert.equal(new Date(period('2026-09-28T02:00:00Z',660).closesAt).toISOString(),'2026-09-29T02:00:00.000Z')
 assert.equal(period('2026-12-31T14:59:59Z',null).businessDate,'2026-12-31')
 assert.equal(new Date(period('2026-12-31T15:00:00Z',null).closesAt).toISOString(),'2027-01-01T15:00:00.000Z')
 const policy={shippingFreeThresholdYen:2400,shippingPolicyFeeYen:500,taxRate:10}
 assert.equal(totals(policy,0).shippingFeeYen,500)
 assert.equal(totals(policy,2399).shippingFeeYen,500)
 assert.equal(totals(policy,2400).shippingFeeYen,0)
 assert.equal(totals({...policy,status:'CANCELLED'},0).totalYen,0)
 assert.throws(()=>totals(policy,2147483640))
 // Close only this isolated fixture's previous batch; no production clocks or orders are touched.
 await exec('UPDATE "WholesaleOrder" SET "consolidationClosesAt"=clock_timestamp()-interval \'1 minute\' WHERE "consolidationClosesAt" IS NOT NULL')
 const cut=await get('order-cutoff');await act('order-cutoff',a,{cutoffTime:'11:00',expectedUpdatedAt:cut.updatedAt})
 const initial=await get('shipping-policy');assert.equal(initial.feeYen,0)
 assert.equal((await req('/api/dealer/erp/shipping-policy',staff,{...initial,feeYen:500,freeThresholdYen:2400,key:crypto.randomUUID()})).status,403)
 let saved=await act('shipping-policy',a,{feeYen:500,freeThresholdYen:2400,expectedUpdatedAt:initial.updatedAt})
 assert.equal((await req('/api/dealer/erp/shipping-policy',a,{feeYen:600,freeThresholdYen:2400,expectedUpdatedAt:initial.updatedAt,key:crypto.randomUUID()})).status,409)
 assert.equal((await get('shipping-policy',b)).feeYen,0)
 let payload=cart(1),q=await quote(payload)
 assert.equal(q.orders[0].shippingFeeYen,500);assert.equal(q.orders[0].totalYen,1430)
 payload.quoteToken=q.quoteToken
 const retries=await Promise.all([submit(payload),submit(payload)]),id=retries[0].order.id
 assert.equal(retries[1].order.id,id)
 const accepted=await ok('/api/dealer/orders/'+id+'/status',a,{status:'ACCEPTED'})
 assert.equal(accepted.order?.totalYen??accepted.totalYen??(await sql('SELECT "totalYen" FROM "WholesaleOrder" WHERE id=$1',id))[0].totalYen,1430)
 assert.equal((await sql('SELECT quantity FROM "WholesaleOrderLine" WHERE "orderId"=$1',id))[0].quantity,1)
 assert.equal((await req('/api/admin/wholesale/orders','',{...payload,lines:[{dealerProductId:'product-a',quantity:2}]},sh)).status,409)
 const staleCart=cart(1),stale=await quote(staleCart)
 const second=await submit(cart(1));assert.equal(second.order.id,id);assert.equal(second.order.merged,true);assert.equal(second.order.totalYen,2310)
 assert.equal((await req('/api/admin/wholesale/orders','',{...staleCart,quoteToken:stale.quoteToken},sh)).status,409)
 const third=await submit(cart(1));assert.equal(third.order.id,id);assert.equal(third.order.shippingFeeYen,0);assert.equal(third.order.totalYen,2640)
 const line=(await sql('SELECT * FROM "WholesaleOrderLine" WHERE "orderId"=$1',id))[0]
 const view=await get('order-amendment?id='+id)
 const amended=await act('order-amend',a,{orderId:id,version:view.version,lines:[{lineId:line.id,quantity:1}],requestedDeliveryDate:'',salonNote:''})
 assert.equal(amended.totalYen,1430)
 saved=await act('shipping-policy',a,{feeYen:900,freeThresholdYen:10000,expectedUpdatedAt:saved.updatedAt})
 const retained=await quote(cart(1));assert.equal(retained.orders[0].shippingFeeYen,500);assert.equal(retained.orders[0].shippingFreeThresholdYen,2400)
 await act('stock',a,{locationId:wh.locationId,productId:'product-a',kind:'RECEIPT',quantity:20,reason:'fixture'})
 await act('reserve',a,{orderId:id,lineId:line.id,locationId:wh.locationId,quantity:1})
 assert.equal((await req('/api/dealer/erp/ship',a,{orderId:id,key:crypto.randomUUID()})).status,409)
 const concurrent=await Promise.all([submit(cart(1)),submit(cart(1))]);assert.ok(concurrent.every(r=>r.order.id===id))
 assert.equal((await sql('SELECT quantity FROM "WholesaleOrderLine" WHERE id=$1',line.id))[0].quantity,3)
 // Freeze a below-threshold batch for partial-shipment freight accounting.
 let v=await get('order-amendment?id='+id)
 await act('order-amend',a,{orderId:id,version:v.version,lines:[{lineId:line.id,quantity:2}],requestedDeliveryDate:'',salonNote:''})
 await exec('UPDATE "WholesaleOrder" SET "consolidationClosesAt"=clock_timestamp()-interval \'1 minute\' WHERE id=$1',id)
 await exec('UPDATE "WholesaleOrderAmendment" SET "cutoffAt"=clock_timestamp()-interval \'1 minute\' WHERE "orderId"=$1',id)
 const next=await submit(cart(1));assert.notEqual(next.order.id,id);assert.equal(next.order.shippingFeeYen,900)
 assert.equal((await req('/api/dealer/erp/order-amend',a,{orderId:id,version:v.version,lines:[{lineId:line.id,quantity:3}],key:crypto.randomUUID()})).status,409)
 await act('reserve',a,{orderId:id,lineId:line.id,locationId:wh.locationId,quantity:1})
 const shipment1=await act('ship',a,{orderId:id});await act('deliver',a,{shipmentId:shipment1.id})
 await act('reserve',a,{orderId:id,lineId:line.id,locationId:wh.locationId,quantity:1})
 const shipment2=await act('ship',a,{orderId:id});await act('deliver',a,{shipmentId:shipment2.id})
 const charges=await sql('SELECT * FROM "DealerErpCharge" WHERE "orderId"=$1',id)
 assert.equal(charges.filter(c=>c.category==='送料').length,1)
 assert.equal(charges.reduce((n,c)=>n+c.quantity*c.unitPrice,0),2100)
 const notes=await Promise.all([req('/dealer/erp/shipment/'+shipment1.id,a),req('/dealer/erp/shipment/'+shipment2.id,a),req('/dealer/orders/'+id+'/delivery-note',a)])
 assert.ok(notes.every(n=>n.status===200));assert.equal(notes[0].content,notes[1].content);assert.equal(notes[0].content,notes[2].content)
 assert.match(notes[0].content,/2,000円/);assert.doesNotMatch(notes[0].content,/500円|割引/)
 assert.equal((await req('/dealer/orders/'+id+'/delivery-note',b)).status,404)
 const day=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date())
 const invoice=await act('invoice',a,{organizationId:'salon-a',closingDate:day,dueDate:day})
 const inv=(await sql('SELECT * FROM "DealerErpInvoice" WHERE id=$1',invoice.id))[0]
 assert.match((await req('/dealer/erp/invoice/'+invoice.id,a)).content,/送料/)
 assert.equal(Number(inv.totalYen),1430,'Existing unbilled credit -800 plus merchandise 1600 and freight 500, with 10% tax')
 const delivered=await get('order?id='+id)
 await act('return',a,{shipmentId:shipment1.id,lineId:delivered.shipments.find(s=>s.id===shipment1.id).lines[0].id,quantity:1,restock:true,reason:'fixture return'})
 const afterReturn=await sql('SELECT * FROM "DealerErpCharge" WHERE "orderId"=$1',id)
 assert.equal(afterReturn.filter(c=>c.category==='送料').length,1)
 assert.equal(afterReturn.reduce((n,c)=>n+c.quantity*c.unitPrice,0),1300,'Goods-only return does not create/refund freight')
 v=await get('order-amendment?id='+next.order.id)
 await act('order-cancel',a,{orderId:next.order.id,version:v.version})
 const cancelled=(await sql('SELECT * FROM "WholesaleOrder" WHERE id=$1',next.order.id))[0]
 assert.equal(cancelled.shippingFeeYen,0);assert.equal(cancelled.totalYen,0)
 const legacyCancel=(await submit(cart(1))).order
 await ok('/api/dealer/orders/'+legacyCancel.id+'/status',a,{status:'CANCELLED'})
 assert.equal((await sql('SELECT "totalYen" FROM "WholesaleOrder" WHERE id=$1',legacyCancel.id))[0].totalYen,0)
 await exec('UPDATE "WholesaleOrder" SET "businessDate"=\'2030-01-01\'::date WHERE id=$1',id)
 const calendar=await ok('/api/dealer/calendar?month=2030-01',a)
 assert.equal(calendar.calendar.days.find(d=>d.date==='2030-01-01').invoiceCount,1,'Calendar uses business date instead of receipt date')
 assert.equal((await req('/api/admin/wholesale/order-quote','',cart(1),{...sh,Origin:'https://evil.example'})).status,403)
 assert.equal((await req('/api/admin/wholesale/order-quote','',cart(1))).status,401)
 console.log('PASS v692: JST cutoffs, merge/idempotency/concurrency, stale quote, shipping snapshots, edits/cancel, partial delivery single freight, consolidated delivery note, permissions')
}
