import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import {createRequire} from 'node:module'
const require=createRequire('/app/package.json'),{cutoffAt}=require('/app/order-amendments-v687.js')
export async function verify({db,req,ok,a,b,staff,makeOrder,wh,employee}){
 const sql=(s,...p)=>db.$queryRawUnsafe(s,...p),run=(s,...p)=>db.$executeRawUnsafe(s,...p),headers={'x-fixture-salon':'1'}
 const get=(name,cookie=a)=>ok('/api/dealer/erp/'+name,cookie)
 const command=(name,p,cookie=a,key=crypto.randomUUID())=>ok('/api/dealer/erp/'+name,cookie,{...p,key})
 const salonGet=id=>ok('/api/admin/wholesale/erp/order-amendment?dealer=dealer-a&id='+id,'',undefined,headers)
 const salonPost=(name,p,key=crypto.randomUUID())=>ok('/api/admin/wholesale/erp/'+name+'?dealer=dealer-a','',{...p,key},headers)
 const denied=async(name,p,status=409,cookie=a)=>assert.equal((await req('/api/dealer/erp/'+name,cookie,{...p,key:crypto.randomUUID()})).status,status,name)
 assert.equal((await get('order-cutoff')).configured,false)
 assert.equal((await get('order-cutoff',staff)).canManage,false)
 await denied('order-cutoff',{cutoffTime:'11:00'},403,staff)
 await denied('order-cutoff',{cutoffTime:'24:00'},400)
 assert.equal((await req('/api/admin/wholesale/erp/order-cutoff?dealer=dealer-a','',{key:crypto.randomUUID(),cutoffTime:'11:00'},headers)).status,404)
 assert.equal((await req('/api/dealer/erp/order-cutoff',a,{key:crypto.randomUUID(),cutoffTime:'11:00'},{Origin:'https://evil.example'})).status,403)
 for(const [id,time] of [['before','2026-01-31T10:59:59.999+09:00'],['equal','2026-01-31T11:00:00+09:00'],['after','2026-01-31T11:00:00.001+09:00']]){
  await makeOrder('cutoff-'+id);await run('UPDATE "WholesaleOrder" SET "orderedAt"=$2 WHERE id=$1','cutoff-'+id,new Date(time))
 }
 let policy=await command('order-cutoff',{cutoffTime:'11:00',expectedUpdatedAt:null})
 const snapshots=await sql('SELECT a.*,o."orderedAt" FROM "WholesaleOrderAmendment" a JOIN "WholesaleOrder" o ON o.id=a."orderId" WHERE o.id LIKE \'cutoff-%\' ORDER BY o.id')
 for(const s of snapshots)assert.equal(s.cutoffAt.toISOString(),cutoffAt(s.orderedAt,660).toISOString())
 assert.equal((await get('order-cutoff',b)).configured,false,'Policy scoped to dealer')
 await denied('order-cutoff',{cutoffTime:'12:00',expectedUpdatedAt:null})
 const minute=(new Date().getUTCHours()*60+new Date().getUTCMinutes()+540+120)%1440,cutoffTime=String(Math.floor(minute/60)).padStart(2,'0')+':'+String(minute%60).padStart(2,'0')
 policy=await command('order-cutoff',{cutoffTime,expectedUpdatedAt:policy.updatedAt})
 assert.deepEqual(await sql('SELECT a.*,o."orderedAt" FROM "WholesaleOrderAmendment" a JOIN "WholesaleOrder" o ON o.id=a."orderId" WHERE o.id LIKE \'cutoff-%\' ORDER BY o.id'),snapshots,'Settings changes cannot reopen existing orders')
 for(const id of ['cutoff-before','cutoff-equal','cutoff-after']){
  const d=await salonGet(id);assert.equal(d.canEdit,false);assert.equal(d.canCancel,false)
  await denied('order-cancel',{orderId:id,version:d.version})
  await denied('order-edit',{orderId:id,kind:'CANCEL',reason:'bypass'})
  assert.equal((await req('/api/dealer/orders/'+id+'/status',a,{status:'CANCELLED'})).status,409)
  assert.equal((await req('/api/dealer/orders/'+id+'/status',a,{status:'ORDERED',lines:[{id:id+'-line',unitPrice:700,deliveredQuantity:2}]})).status,409)
 }
 const legacy=await ok('/api/dealer/orders/cutoff-before',a)
 assert.equal(legacy.cutoffOpen,false)
 await ok('/api/dealer/orders/cutoff-before/status',a,{status:'ACCEPTED',lines:legacy.lines.map(l=>({id:l.id,unitPrice:l.unitPrice,deliveredQuantity:l.deliveredQuantity,productCode:l.productCode||'',janCode:l.janCode||''}))})
 assert.equal((await get('order?id=cutoff-before')).order.status,'ACCEPTED','Acceptance without line changes remains allowed after cutoff')
 await run(`INSERT INTO "WholesaleDealerProduct" (id,"dealerId","manufacturerName",name,"productCode","wholesalePrice","orderUnit") VALUES ('product-c','dealer-a','メーカー','追加商品','SKU-C',500,2)`)
 await run(`INSERT INTO "WholesaleContractProductPrice" (id,"contractId","dealerProductId","discountRate") VALUES ('qa-price-c','contract-a','product-c',10)`)
 const created=await ok('/api/admin/wholesale/orders','',{dealerId:'dealer-a',lines:[{dealerProductId:'product-a',quantity:2}]},headers)
 const orderId=created.order?.id||created.id
 assert.ok(orderId,JSON.stringify(created))
 let d=await salonGet(orderId);assert.ok(d.canEdit);assert.ok(d.cutoffAt)
 assert.equal(d.cutoffAt,cutoffAt(d.order.orderedAt,minute).toISOString())
 assert.equal((await req('/api/dealer/erp/order-amendment?id='+orderId,b)).status,404)
 assert.equal((await req('/api/admin/wholesale/erp/order-amendment?dealer=dealer-a&id=order-other','',undefined,headers)).status,404)
 await denied('order-amend',{orderId,version:d.version,lines:[{dealerProductId:'product-b',quantity:1}]},409)
 await denied('order-amend',{orderId,version:d.version,lines:[{dealerProductId:'product-c',quantity:1}]},400)
 await denied('order-amend',{orderId,version:d.version,lines:[]},400)
 await denied('order-amend',{orderId,version:d.version,lines:[{lineId:d.lines[0].id,quantity:2},{dealerProductId:'product-a',quantity:1}]},400)
 const key=crypto.randomUUID(),body={orderId,version:d.version,lines:[{lineId:d.lines[0].id,quantity:3},{dealerProductId:'product-c',quantity:2}],requestedDeliveryDate:'2026-12-12',salonNote:'変更メモ'}
 await salonPost('order-amend',body,key);await salonPost('order-amend',body,key)
 let updated=await salonGet(orderId)
 assert.equal(updated.order.totalYen,3630);assert.equal(updated.order.requestedDeliveryDate.slice(0,10),'2026-12-12');assert.equal(updated.order.salonNote,'変更メモ');assert.equal(updated.lines.length,2)
 assert.equal(updated.order.status,'ORDERED')
 await denied('order-amend',body)
 await run('UPDATE "WholesaleContractProductPrice" SET "discountRate"=50 WHERE id=\'qa-price-a\'')
 await command('reserve',{orderId,lineId:updated.lines[0].id,locationId:wh.locationId,quantity:1})
 updated=await salonGet(orderId)
 assert.equal(updated.lines[0].reserved,1)
 await command('order-amend',{orderId,version:updated.version,lines:[{lineId:updated.lines.find(l=>l.dealerProductId==='product-a').id,quantity:4}],salonNote:'担当者が修正',requestedDeliveryDate:''},staff)
 updated=await salonGet(orderId)
 assert.equal(updated.lines.find(l=>l.dealerProductId==='product-a').unitPrice,800,'Existing price preserved')
 assert.equal(updated.order.totalYen,3520);assert.equal(updated.lines.reduce((n,l)=>n+l.reserved,0),0)
 assert.equal(updated.lines.find(l=>l.dealerProductId==='product-c').editableQuantity,0)
 const history=(await ok('/api/admin/wholesale/bootstrap?dealerId=all','',undefined,headers)).orders.find(o=>o.id===orderId)
 assert.equal(history.lineCount,1);assert.equal(history.totalQuantity,4);assert.equal(history.dealerId,'dealer-a')
 assert.equal(history.cutoffAt,updated.cutoffAt)
 const oldVersion=updated.version
 const races=await Promise.all([2,3].map(quantity=>req('/api/dealer/erp/order-amend',a,{key:crypto.randomUUID(),orderId,version:oldVersion,lines:[{lineId:updated.lines.find(l=>l.dealerProductId==='product-a').id,quantity}]})))
 assert.deepEqual(races.map(r=>r.status).sort(),[200,409])
 updated=await salonGet(orderId)
 await salonPost('order-cancel',{orderId,version:updated.version})
 updated=await salonGet(orderId);assert.equal(updated.order.status,'CANCELLED');assert.equal(updated.order.totalYen,0);assert.equal(updated.canEdit,false)
 assert.equal((await sql('SELECT COUNT(*)::int AS n FROM "WholesaleOrderEvent" WHERE "orderId"=$1 AND "eventType"=\'ORDER_AMENDED\'',orderId))[0].n,3,'Idempotency and rejected edits create no duplicate audit')
 for(const id of ['order-ten','order-other'])assert.equal((await get('order-amendment?id='+id)).canEdit,false)
 const pastVersion=await salonGet('cutoff-before')
 assert.equal((await req('/api/admin/wholesale/erp/order-cancel?dealer=dealer-a','',{key:crypto.randomUUID(),orderId:'cutoff-before',version:pastVersion.version},{...headers,Origin:'https://evil.example'})).status,403)
 // A transaction that began before the deadline must still check the current clock after waiting.
 await makeOrder('waiting');await run('INSERT INTO "WholesaleOrderAmendment" ("orderId","cutoffAt") VALUES (\'waiting\',clock_timestamp()+INTERVAL \'1 second\')')
 let releaseLock,lockReady
 const ready=new Promise(r=>lockReady=r),gate=new Promise(r=>releaseLock=r)
 const held=db.$transaction(async tx=>{await tx.$executeRawUnsafe("SELECT pg_advisory_xact_lock(hashtextextended('dealer-erp:' || $1,0))",'dealer-a');lockReady();await gate})
 await ready;const waiting=await salonGet('waiting')
 const pending=req('/api/dealer/erp/order-cancel',a,{key:crypto.randomUUID(),orderId:'waiting',version:waiting.version})
 await new Promise(r=>setTimeout(r,1300));releaseLock();await held;assert.equal((await pending).status,409)
 // New split orders capture independent snapshots from each dealer's configuration.
 await run('UPDATE "WholesaleDealerContract" SET status=\'ACTIVE\' WHERE "dealerId"=\'dealer-b\' AND "organizationId"=\'salon-a\'')
 await command('order-cutoff',{cutoffTime:'23:59',expectedUpdatedAt:null},b)
 const split=await ok('/api/admin/wholesale/orders','',{orders:[{dealerId:'dealer-a',lines:[{dealerProductId:'product-a',quantity:1}]},{dealerId:'dealer-b',lines:[{dealerProductId:'product-b',quantity:1}]}]},headers)
 const saved=await sql('SELECT a.*,o."orderedAt",o."dealerId" FROM "WholesaleOrderAmendment" a JOIN "WholesaleOrder" o ON o.id=a."orderId" WHERE a."orderId"=ANY($1::text[])',split.orders.map(o=>o.id))
 assert.equal(saved.length,2);for(const s of saved)assert.equal(s.cutoffAt.toISOString(),cutoffAt(s.orderedAt,s.dealerId==='dealer-a'?minute:1439).toISOString())
 console.log('v687 integration PASS: both histories, add/remove/quantity/date/note, immutable prices/cutoffs, Japanese boundary backfill, role/tenant/CSRF, idempotency, audit, stock release, stale/concurrent edits, all cancellation routes and lock-wait deadline')
}
