FROM 009293460979.dkr.ecr.ap-northeast-1.amazonaws.com/salon-de-lien-staging-app:staff-chat-ui-20260812-01
USER root
COPY patch-customer-tabs.js /tmp/patch-customer-tabs.js
RUN node /tmp/patch-customer-tabs.js
USER nextjs
WORKDIR /app
CMD ["node", "server.js"]
