import assert from 'node:assert/strict'
import crypto from 'node:crypto'
export async function verify({ action, denied, get, sql, a, b, staff, req, ok, employee, salonThread, internal }) {
  const sh = { 'x-fixture-salon': '1' }
  const salon = (name, data, dealer = 'dealer-a') => ok('/api/admin/wholesale/erp/' + name + (name.includes('?') ? '&' : '?') + 'dealer=' + dealer, '', data && { ...data, key: data.key || crypto.randomUUID() }, sh)
  assert.equal((await get('chat-partners', a)).total, 2, 'Partners without a thread are listed')
  assert.deepEqual((await get('chat-partners', staff)).rows.map(p => p.id), ['salon-a'])
  assert.equal((await get('chat-partners?member=' + employee.id, a)).total, 1)
  assert.equal((await get('chat-partners?search=' + encodeURIComponent('テストサロン'), a)).total, 2)
  assert.equal((await get('chat-partners?search=' + encodeURIComponent('%_'), a)).total, 0, 'Search is literal')
  const old = await get('chat-messages?partner=salon-a', staff)
  assert.equal(old.rows.length, 2, 'Existing order chat is retained')
  assert.equal(old.rows[0].orderNo, 'order-ten')
  assert.ok(old.rows.every(m => m.threadId !== internal.id), 'No internal chat in partner view')
  await denied('chat-send', staff, { partner: 'salon-b', body: 'forbidden' }, 404)
  await denied('chat-send', b, { partner: 'salon-a', body: 'foreign' }, 404)
  assert.equal((await req('/api/dealer/erp/chat-messages?partner=salon-b', staff)).status, 404)
  assert.equal((await req('/api/dealer/erp/chat-partners')).status, 401)
  assert.equal((await req('/api/dealer/erp/chat-send', a, { partner: 'salon-a', body: 'csrf', key: crypto.randomUUID() }, { Origin: 'https://evil.example' })).status, 403)
  const key = crypto.randomUUID(), payload = { partner: 'salon-a', body: '本日の納品について確認いたします。' }
  const duplicate = await Promise.all([action('chat-send', staff, payload, key), action('chat-send', staff, payload, key)])
  assert.equal(duplicate[0].id, duplicate[1].id, 'Retries are exactly once')
  await denied('chat-send', a, { partner: 'salon-a', body: '' }, 400)
  await denied('chat-send', a, { partner: 'salon-a', body: 'x'.repeat(4001) }, 400)
  await salon('chat-send', { partner: 'dealer-a', body: 'ありがとうございます。午後の納品でお願いします。' })
  assert.equal((await get('chat-partners?unread=1', staff)).counts.unreadCount, 1)
  const current = await get('chat-messages?partner=salon-a', staff)
  const cursor = current.rows.at(-1).id
  await salon('chat-send', { partner: 'dealer-a', body: '追加の確認です。' })
  await action('chat-read', staff, { partner: 'salon-a', messageId: cursor })
  assert.equal((await get('chat-partners', staff)).rows[0].unread, 1, 'Read cursor must not consume later messages')
  await action('chat-send', a, { partner: 'salon-b', body: 'サロンB専用' })
  const other = await get('chat-messages?partner=salon-b', a)
  await denied('chat-read', staff, { partner: 'salon-a', messageId: other.rows[0].id }, 404)
  assert.equal((await salon('chat-messages?partner=dealer-a')).rows.some(m => m.body === 'サロンB専用'), false)
  await sql(`INSERT INTO "WholesaleDealerContract" (id,"dealerId","organizationId",status,"customerCode") VALUES ('chat-contract-b','dealer-b','salon-a','ACTIVE','B-A')`)
  await action('chat-send', b, { partner: 'salon-a', body: 'ディーラーB専用' })
  assert.equal((await salon('chat-partners')).total, 2)
  assert.equal((await salon('chat-messages?partner=dealer-b', undefined, 'dealer-b')).rows.length, 1)
  assert.equal((await salon('chat-messages?partner=dealer-a')).rows.some(m => m.body === 'ディーラーB専用'), false)
  assert.equal((await req('/api/admin/wholesale/erp/chat-messages?dealer=dealer-a&partner=dealer-b', '', undefined, sh)).status, 404)
  await sql(`UPDATE "WholesaleDealerContract" SET status='PENDING' WHERE id='contract-a'`)
  assert.equal((await get('chat-partners', staff)).total, 0)
  await denied('chat-send', staff, payload, 404)
  assert.equal((await req('/api/dealer/erp/chat-messages?partner=salon-a', a)).status, 404)
  assert.equal((await req('/api/admin/wholesale/erp/chat-partners?dealer=dealer-a', '', undefined, sh)).status, 403)
  await denied('message', staff, { threadId: salonThread.id, body: 'legacy bypass' }, 403)
  await sql(`UPDATE "WholesaleDealerContract" SET status='ACTIVE' WHERE id='contract-a'`)
  await sql(`UPDATE "WholesaleDealer" SET active=FALSE WHERE id='dealer-b'`)
  assert.equal((await salon('chat-partners')).total, 1)
  await sql(`UPDATE "WholesaleDealer" SET active=TRUE WHERE id='dealer-b'`)
  for (let i = 0; i < 64; i++) await action('chat-send', staff, { partner: 'salon-a', body: '履歴確認 ' + i })
  const last = await get('chat-messages?partner=salon-a', staff)
  assert.equal(last.rows.length, 50); assert.equal(last.more, true)
  const earlier = await get('chat-messages?partner=salon-a&before=' + last.rows[0].id, staff)
  assert.ok(earlier.rows.length > 0 && !earlier.more)
  assert.ok(Number(earlier.rows.at(-1).id) < Number(last.rows[0].id))
  const incremental = await get('chat-messages?partner=salon-a&after=' + earlier.rows[0].id, staff)
  assert.equal(incremental.rows.length, 50); assert.equal(incremental.more, true)
  assert.ok(Number(incremental.rows[0].id) < Number(incremental.rows.at(-1).id))
  assert.equal((await sql(`SELECT COUNT(*)::int AS count FROM "DealerErpThread" WHERE "dealerId"='dealer-a' AND "organizationId"='salon-a' AND subject='サロン・ディーラーチャット'`))[0].count, 1)
  for (let i = 0; i < 31; i++) {
    await sql('INSERT INTO "Organization" (id,name) VALUES ($1,$2)', 'page-' + i, 'ページング ' + i)
    await sql('INSERT INTO "WholesaleDealerContract" (id,"dealerId","organizationId",status,"customerCode") VALUES ($1,\'dealer-a\',$1,\'ACTIVE\',$1)', 'page-' + i)
  }
  assert.equal((await get('chat-partners', a)).rows.length, 30)
  assert.equal((await get('chat-partners?page=2', a)).rows.length, 3)
  await sql(`DELETE FROM "WholesaleDealerContract" WHERE id LIKE 'page-%'`)
  await sql(`DELETE FROM "Organization" WHERE id LIKE 'page-%'`)
  const salonPage = await req('/admin/dealer-messages?dealer=dealer-a', '', undefined, sh)
  assert.ok(salonPage.content.includes('ディーラーとのチャット'))
  assert.ok((await req('/dealer/messages', a)).content.includes('契約サロンとのチャット'))
  assert.equal((await req('/dealer-erp-v678-partner-chat-client-v682.js')).status, 200)
  assert.equal((await req('/dealer-erp-v678-order-entry-v682.js')).status, 200)
  console.log('PASS: partner chat history, two-way messaging, retry deduplication, read cursors, pagination, active contracts, staff isolation, CSRF and dealer separation')
}
