import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
const require=createRequire('/app/package.json')
const {applyInTransaction}=require('/app/customer-booking-points-v652')
const {bookingContext,assertCampaignMenu}=require('/app/campaign-booking-v685.cjs')
export async function verify({db,service,api,session}){
 const run=(sql,...args)=>db.$executeRawUnsafe(sql,...args)
 await run('CREATE TABLE "CustomerCampaign" (id TEXT PRIMARY KEY,"organizationId" TEXT,title TEXT,"targetMenu" TEXT,"discountRate" INTEGER,"startsAt" TIMESTAMPTZ,"endsAt" TIMESTAMPTZ,status TEXT)')
 await run('CREATE TABLE "SalonMenu" (id TEXT PRIMARY KEY,"organizationId" TEXT,name TEXT,active BOOLEAN,source TEXT,"sortOrder" INTEGER)')
 await run(`INSERT INTO "SalonMenu" VALUES ('cut','org-a','カット',true,'manual',0),('color','org-a','カラー',true,'manual',0)`)
 await run(`INSERT INTO "CustomerCampaign" VALUES ('campaign-a','org-a','カット20%OFF','カット',20,NOW()-INTERVAL '1 day',NOW()+INTERVAL '1 day','published'),('free','org-a','無料','カット',100,NOW()-INTERVAL '1 day',NOW()+INTERVAL '1 day','published'),('event','org-a','イベント',NULL,NULL,NOW()-INTERVAL '1 day',NOW()+INTERVAL '1 day','published')`)
 const book=(id,{campaignId='campaign-a',points=0,coupon='',menu='cut',price=5500}={})=>db.$transaction(async tx=>{
  const campaign=await assertCampaignMenu(tx,session,campaignId,menu)
  await tx.$executeRawUnsafe(`INSERT INTO "Appointment" (id,"customerId","scheduledAt",menu,"estimatedPrice",status,"bookingProvider",note) VALUES ($1,'customer-a',NOW()+INTERVAL '3 days','カット',$2,'予約確定','customer_app','')`,id,price)
  return applyInTransaction(tx,session,{appointmentId:id,couponIssueId:coupon,pointsToUse:points},campaign)
 },{isolationLevel:'Serializable'})
 const stored=async id=>(await db.$queryRawUnsafe('SELECT * FROM "Appointment" WHERE id=$1',id))[0]
 const balance=async()=>(await db.$queryRawUnsafe('SELECT "availablePoints" FROM "CustomerPointAccount" WHERE "customerId"=\'customer-a\''))[0].availablePoints
 assert.equal((await bookingContext(db,session,'campaign-a')).campaign.discountRate,20)
 const base=await book('campaign-base');assert.equal(base.menuPrice,5500);assert.equal(base.campaignDiscount,1100);assert.equal(base.finalPrice,4400)
 assert.equal((await stored('campaign-base')).estimatedPrice,4400);assert.match((await stored('campaign-base')).note,/キャンペーン割引: 1,100円/)
 const admin=await api(service,'GET','/api/lien-admin-appointment-coupon?appointmentId=campaign-base')
 assert.equal(admin.body.campaignTitle,'カット20%OFF');assert.equal(admin.body.finalPrice,4400)
 const retry=await api(service,'POST','/api/lien-customer-booking-coupon',{appointmentId:'campaign-base',pointsToUse:0})
 assert.equal(retry.body.finalPrice,4400,'Do not apply the discount twice')
 const before=await balance(),points=await book('campaign-points',{points:760})
 assert.equal(points.finalPrice,3640);assert.equal(points.campaignDiscount,1100);assert.equal(await balance(),before-760)
 await run('UPDATE "Appointment" SET status=\'キャンセル\' WHERE id=\'campaign-points\'')
 assert.equal(await balance(),before)
 await run('UPDATE "Appointment" SET status=\'キャンセル\' WHERE id=\'campaign-points\'')
 assert.equal(await balance(),before,'Single refund on repeated cancel')
 await assert.rejects(()=>book('bad-points',{points:99999}),/ポイント/)
 assert.equal(await stored('bad-points'),undefined,'Campaign booking is rolled back atomically')
 assert.equal(await balance(),before)
 await run(`INSERT INTO "CouponIssue" (id,"customerId","couponCode","customerName","discountRate","targetMenusJson","issuedAt","expiresAt") VALUES ('other-coupon','customer-a','TEN','customer',10,'[]',NOW()-INTERVAL '1 day',NOW()+INTERVAL '1 day')`)
 const exclusive=await book('campaign-coupon',{coupon:'other-coupon',points:760})
 assert.equal(exclusive.campaignDiscount,0);assert.equal(exclusive.couponDiscount,550);assert.equal(exclusive.finalPrice,4190)
 await run('UPDATE "Appointment" SET status=\'キャンセル\' WHERE id=\'campaign-coupon\'')
 assert.equal((await db.$queryRawUnsafe('SELECT status FROM "CouponIssue" WHERE id=\'other-coupon\''))[0].status,'issued')
 assert.equal((await book('free-booking',{campaignId:'free'})).finalPrice,0)
 assert.equal((await book('event-booking',{campaignId:'event'})).finalPrice,5500)
 assert.equal((await book('round-booking',{price:5555})).finalPrice,4444)
 await assert.rejects(()=>book('wrong-menu',{menu:'color'}),/対象メニュー/)
 assert.equal(await stored('wrong-menu'),undefined)
 await run('UPDATE "CustomerCampaign" SET "endsAt"=NOW()-INTERVAL \'1 hour\' WHERE id=\'campaign-a\'')
 await assert.rejects(()=>book('expired-booking'),/終了/)
 assert.equal(await stored('expired-booking'),undefined)
 await run(`INSERT INTO "ServiceSale" (id,"customerId","appointmentId",title,amount) VALUES ('campaign-sale','customer-a','campaign-base','カット',4400)`)
 assert.equal((await db.$queryRawUnsafe('SELECT status FROM "CustomerBookingAdjustmentV652" WHERE "appointmentId"=\'campaign-base\''))[0].status,'settled')
 assert.equal((await api(service,'GET','/api/lien-admin-appointment-coupon?appointmentId=campaign-base',null,async()=>({organizationId:'org-b'}))).status,404)
 console.log('v697 integration PASS: 5500->4400->3640, coupon exclusion, 100%/no-rate/rounding, atomic failure, idempotency, expiry/target/tenant checks, cancellation refunds and salon settlement')
}
