import assert from 'node:assert/strict'
export async function verify({db,req,ok,a,b,staff}){
 const run=(q,...p)=>db.$executeRawUnsafe(q,...p)
 await run('CREATE TABLE IF NOT EXISTS "OrganizationStoreProfile" ("organizationId" TEXT PRIMARY KEY,phone TEXT,"postalCode" TEXT,prefecture TEXT,city TEXT,"addressLine1" TEXT,"addressLine2" TEXT)')
 const add=async(id,maker,category,active=true,dealer='dealer-a')=>run('INSERT INTO "WholesaleDealerProduct" (id,"dealerId","manufacturerName",name,category,"productCode","wholesalePrice",active) VALUES ($1,$2,$3,$4,$5,$6,1000,$7)',id,dealer,maker,id==='nakano-0'?'ナカノ ワックス':id,category,id,active)
 for(let i=0;i<35;i++)await add('nakano-'+i,'中野製薬','スタイリング')
 await add('nakano-care','中野製薬','ヘアケア')
 await add('milbon-tool','ミルボン','GM(ﾂｰﾙ)')
 await add('milbon-care','ミルボン','ヘアケア')
 await add('hidden','中野製薬','非公開種別',false)
 await add('foreign','中野製薬','他社専用',true,'dealer-b')
 await add('empty','種別なしメーカー',null)
 const fetchKind=(kind,params={},cookie=a)=>ok('/api/dealer/bootstrap?'+new URLSearchParams({view:kind,...params}),cookie)
 assert.equal((await req('/api/dealer/bootstrap?view=products')).status,401)
 for(const [view,prefix] of [['products','product'],['pricing','pricing']]){
  const initial=await fetchKind(view)
  assert.ok(initial.productFilters.categories.includes('GM(ﾂｰﾙ)'))
  assert.ok(!initial.productFilters.categories.includes('他社専用'))
  assert.ok(!initial.productFilters.categories.includes('非公開種別'))
  const filtered=await fetchKind(view,{[prefix+'Manufacturer']:'中野製薬'})
  assert.deepEqual(filtered.productFilters.categories,['スタイリング','ヘアケア'])
  assert.ok(filtered.products.every(p=>p.manufacturerName==='中野製薬'))
  assert.equal(filtered[prefix+'Pagination'].totalCount,36)
  assert.equal(filtered.products.length,30)
  assert.equal(filtered.productFilters.categoryGroups.filter(r=>r.manufacturerName==='中野製薬').length,2)
  const valid=await fetchKind(view,{[prefix+'Manufacturer']:'中野製薬',[prefix+'Category']:'ヘアケア'})
  assert.equal(valid[prefix+'Pagination'].category,'ヘアケア');assert.equal(valid.products.length,1)
  const invalid=await fetchKind(view,{[prefix+'Manufacturer']:'中野製薬',[prefix+'Category']:'GM(ﾂｰﾙ)'})
  assert.equal(invalid[prefix+'Pagination'].category,'');assert.equal(invalid[prefix+'Pagination'].totalCount,36)
  const search=await fetchKind(view,{[prefix+'Manufacturer']:'中野製薬',[prefix+'Search']:'ワックス'})
  assert.equal(search.products.length,1);assert.deepEqual(search.productFilters.categories,filtered.productFilters.categories,'Options come from complete manufacturer catalog, not current search/page')
  const last=await fetchKind(view,{[prefix+'Manufacturer']:'中野製薬',[prefix+'Page']:'2'})
  assert.equal(last.products.length,6);assert.deepEqual(last.productFilters.categories,filtered.productFilters.categories)
  const none=await fetchKind(view,{[prefix+'Manufacturer']:'種別なしメーカー'})
  assert.deepEqual(none.productFilters.categories,[]);assert.equal(none.products.length,1)
  const own=await fetchKind(view,{[prefix+'Manufacturer']:'中野製薬'},b)
  assert.deepEqual(own.productFilters.categories,['他社専用']);assert.equal(own.products.length,1)
  const employee=await fetchKind(view,{[prefix+'Manufacturer']:'中野製薬'},staff)
  assert.deepEqual(employee.productFilters.categories,filtered.productFilters.categories)
  assert.match((await req('/dealer/'+view,a)).content,/dealer-catalog-v695\.js\?v=695-1/)
 }
 const normalized=await fetchKind('products',{productSearch:'オルディーブ'})
 assert.equal(normalized.products[0].id,'product-a','Half-width kana search retained')
 console.log('v695 integration PASS: manufacturer-dependent categories, incompatible category reset, shared categories retained, full-catalog facets, search/pagination, blank/inactive categories, tenant/staff scope, immutable client')
}
