import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import http from 'node:http'
import fs from 'node:fs'
import { createRequire } from 'node:module'
if (!process.env.TEST_DATABASE_URL) throw new Error('TEST_DATABASE_URL required; tests use a new isolated schema')
process.env.DEALER_AUTH_SECRET='dealer-erp-v678-fixture-only-secret-0000000000000000000'
const require=createRequire('/app/package.json'), { PrismaClient }=require('@prisma/client')
const { createWholesaleOrderingService }=require('/app/wholesale-ordering-v543.js')
const schema='dealer_erp_'+crypto.randomBytes(8).toString('hex')
const url=new URL(process.env.TEST_DATABASE_URL);url.searchParams.set('connection_limit','10')
const bootstrap=new PrismaClient({ datasources:{ db:{ url:url.href } } })
await bootstrap.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`)
url.searchParams.set('schema',schema)
const db=new PrismaClient({ datasources:{ db:{ url:url.href } } })
const service=createWholesaleOrderingService({ prisma:db,crypto,adminSessionProvider:async req => req.headers['x-fixture-salon'] ? { organizationId:'salon-a',userId:'salon-user' } : null })
const pass='FixtureOnly-v678!'
const hash=p => { const salt=crypto.randomBytes(16).toString('hex');return `scrypt$${salt}$${crypto.scryptSync(p,salt,64).toString('hex')}` }
let base
const server=http.createServer(async(req,res) => {
  try {
    const u=new URL(req.url,'http://localhost')
    if (await service.handle(req,res,u)) return
    const mime={ '.js':'application/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml' }
    const asset='/app/public'+u.pathname
    if (/^\/[a-zA-Z0-9_./-]+$/.test(u.pathname) && !u.pathname.includes('..') && fs.existsSync(asset) && fs.statSync(asset).isFile()) { res.setHeader('Content-Type',mime[u.pathname.slice(u.pathname.lastIndexOf('.'))] || 'application/octet-stream');res.end(fs.readFileSync(asset));return }
    if (u.pathname==='/favicon.ico') { res.statusCode=204;res.end();return }
    res.statusCode=404;res.end('Not found')
  } catch(e) { console.error(e);res.statusCode=500;res.end(e.message) }
})
async function req(path,cookie='',body,headers={}) {
  const r=await fetch(base+path,{ method:body?'POST':'GET',redirect:'manual',headers:{ Cookie:cookie,...(body?{ 'Content-Type':'application/json',Origin:base }:{}),...headers },...(body?{ body:JSON.stringify(body) }:{}) })
  const content=await r.text();let data;try { data=JSON.parse(content) } catch {}
  return { status:r.status,headers:r.headers,content,data }
}
async function ok(path,cookie,body,headers) { const r=await req(path,cookie,body,headers);assert.ok([200,201].includes(r.status),`${path} ${r.status}: ${r.content}`);return r.data }
const action=(name,cookie,p={},key=crypto.randomUUID()) => ok('/api/dealer/erp/'+name,cookie,{ ...p,key })
const denied=(name,cookie,p={},status=403) => req('/api/dealer/erp/'+name,cookie,{ ...p,key:crypto.randomUUID() }).then(r => assert.equal(r.status,status,r.content))
async function login(loginId,password=pass) { const r=await req('/api/dealer/auth/login','',{ loginId,password });assert.equal(r.status,303);const cookie=r.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie,loginId);return cookie }
const sql=(s,...p) => db.$queryRawUnsafe(s,...p)
const get=(path,cookie) => ok('/api/dealer/erp/'+path,cookie)
const now=new Date(), day=new Intl.DateTimeFormat('sv-SE',{ timeZone:'Asia/Tokyo' }).format(now), month=day.slice(0,7)
async function makeOrder(id,org='salon-a',qty=10) {
  await db.$executeRawUnsafe('INSERT INTO "WholesaleOrder" ("id","orderNo","dealerId","organizationId","orderedByName","subtotalYen","taxYen","totalYen") VALUES ($1,$1,\'dealer-a\',$2,\'fixture\',$3,$4,$5)',id,org,qty*800,qty*80,qty*880)
  await db.$executeRawUnsafe('INSERT INTO "WholesaleOrderLine" ("id","orderId","dealerProductId","manufacturerName","productName","category","productCode","unitPrice","listPrice","quantity","deliveredQuantity","lineTotal") VALUES ($1,$2,\'product-a\',\'ミルボン\',\'ｵﾙﾃﾞｨｰﾌﾞ <test>\',\'カラー\',\'SKU-A\',800,1000,$3,$3,$4)',id+'-line',id,qty,qty*800)
}
try {
  await db.$executeRawUnsafe('CREATE TABLE "Organization" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"publicCode" TEXT)')
  await db.$executeRawUnsafe('CREATE TABLE "Product" ("id" TEXT PRIMARY KEY)')
  await db.$executeRawUnsafe('CREATE TABLE "AppUser" ("id" TEXT PRIMARY KEY,"organizationId" TEXT,"displayName" TEXT,"loginId" TEXT,"email" TEXT,"role" TEXT,"active" BOOLEAN DEFAULT TRUE)')
  await service.ensureSchema();await service.ensureSchema()
  for (const id of ['a','b']) await db.$executeRawUnsafe('INSERT INTO "WholesaleDealer" ("id","name","loginId","passwordHash","dealerCode") VALUES ($1,$2,$3,$4,$5)','dealer-'+id,'テストディーラー '+id,'erp-owner-'+id,hash(pass),'ERP-'+id)
  await db.$executeRawUnsafe(`INSERT INTO "Organization" VALUES ('salon-a','テストサロン A','TEST-A'),('salon-b','テストサロン B','TEST-B')`)
  await db.$executeRawUnsafe(`INSERT INTO "AppUser" ("id","organizationId","displayName","role") VALUES ('salon-user','salon-a','サロン担当','ADMIN')`)
  for (const id of ['a','b']) await db.$executeRawUnsafe('INSERT INTO "WholesaleDealerContract" ("id","dealerId","organizationId","status","customerCode","approvedAt") VALUES ($1,\'dealer-a\',$2,\'ACTIVE\',$3,NOW())','contract-'+id,'salon-'+id,id)
  await db.$executeRawUnsafe(`INSERT INTO "WholesaleDealerProduct" ("id","dealerId","manufacturerName","name","category","productCode","wholesalePrice") VALUES ('product-a','dealer-a','ミルボン','ｵﾙﾃﾞｨｰﾌﾞ <test>','カラー','SKU-A',1000),('product-b','dealer-b','他社','商品B','ケア','SKU-B',2000)`)
  await new Promise(resolve => server.listen(Number(process.env.PORT || 3182),'0.0.0.0',resolve));base='http://127.0.0.1:'+server.address().port;process.env.APP_URL=base
  const a=await login('erp-owner-a'),b=await login('erp-owner-b'),opts=await get('options',a)
  const branch=await ok('/api/dealer/team/branch',a,{ name:'岡山営業所' })
  const employee=await ok('/api/dealer/team/member',a,{ name:'営業担当',loginId:'erp-sales-a',role:'STAFF',branchId:branch.id })
  let staff=await login('erp-sales-a',employee.initialPassword)
  assert.equal((await req('/api/dealer/erp/options',staff)).status,428)
  await ok('/api/dealer/staff-password-change',staff,{ currentPassword:employee.initialPassword,newPassword:pass,newPasswordConfirm:pass });staff=await login('erp-sales-a')
  await ok('/api/dealer/team/assignment',a,{ id:'contract-a',memberId:employee.id,branchId:branch.id,closingDay:20 })
  await ok('/api/dealer/team/assignment',a,{ id:'contract-b',memberId:opts.viewer.memberId,closingDay:31 })
  await makeOrder('order-ten');await makeOrder('order-other','salon-b',2)
  assert.equal((await get('products?q='+encodeURIComponent('オルディーブ'),a)).total,1)
  const wh=await action('warehouse',a,{ name:'岡山倉庫',branchId:branch.id,location:'A-1' }),wh2=await action('warehouse',a,{ name:'共通倉庫',location:'B-1' })
  await denied('warehouse',staff,{ name:'forbidden' })
  await denied('stock',a,{ locationId:wh.locationId,productId:'product-b',kind:'RECEIPT',quantity:6,reason:'foreign' },404)
  const receive={ locationId:wh.locationId,productId:'product-a',kind:'RECEIPT',quantity:6,minimum:2,reason:'期首在庫' },key=crypto.randomUUID()
  await Promise.all([action('stock',a,receive,key),action('stock',a,receive,key)])
  assert.equal((await get('inventory',a)).rows[0].onHand,6,'Retry must not double receipt')
  assert.equal((await req('/api/dealer/erp/stock',a,{ ...receive,quantity:7,key })).status,409)
  await denied('reserve',b,{ orderId:'order-ten',lineId:'order-ten-line',locationId:wh.locationId,quantity:1 },404)
  await denied('reserve',staff,{ orderId:'order-other',lineId:'order-other-line',locationId:wh.locationId,quantity:1 },404)
  await denied('reserve',staff,{ orderId:'order-ten',lineId:'order-ten-line',locationId:wh.locationId,quantity:10 },409)
  assert.equal((await sql('SELECT COUNT(*)::int AS n FROM "DealerErpOrder"'))[0].n,0,'Failed adoption rolls back')
  await action('reserve',staff,{ orderId:'order-ten',lineId:'order-ten-line',locationId:wh.locationId,quantity:6 })
  const stock=(await get('inventory',a)).rows[0]
  assert.equal(stock.reserved,6)
  await denied('stock',a,{ ...receive,kind:'COUNT',quantity:0,version:stock.version },409)
  await denied('stock',a,{ ...receive,kind:'COUNT',quantity:10,version:0 },409)
  const ship=await action('ship',staff,{ orderId:'order-ten' })
  let d=await get('order?id=order-ten',staff)
  assert.equal(d.lines[0].shipped,6);assert.equal(d.lines[0].delivered,0);assert.equal(d.order.status,'ACCEPTED')
  assert.equal((await get('inventory',a)).rows[0].onHand,0)
  assert.equal((await get('receivables',a)).unbilled.length,0,'Do not invoice before delivery')
  await action('deliver',staff,{ shipmentId:ship.id })
  await denied('deliver',staff,{ shipmentId:ship.id },409)
  assert.equal((await get('receivables',a)).unbilled[0].amount,4800)
  const r1=await ok('/api/dealer/sales?month='+month,a)
  assert.equal(r1.summary.actualYen,4800,'Partial delivery included in existing sales report')
  assert.equal(r1.summary.forecastYen,9600)
  assert.equal(r1.progress.find(m => m.id===employee.id).actualYen,4800)
  assert.equal((await req('/api/dealer/orders/order-ten/status',a,{ status:'DELIVERED' })).status,409)
  assert.equal((await req('/dealer/orders/order-ten/invoice',a)).status,302)
  await denied('invoice',staff,{ organizationId:'salon-a',closingDate:day,dueDate:day })
  const inv=await action('invoice',a,{ organizationId:'salon-a',closingDate:day,dueDate:day })
  const invoice=(await get('receivables',a)).rows[0]
  assert.equal(invoice.totalYen,5280);assert.equal(invoice.discountYen,1200)
  await denied('invoice',a,{ organizationId:'salon-a',closingDate:day,dueDate:day },409)
  const print=await req('/dealer/erp/invoice/'+inv.id,a)
  assert.equal(print.status,200);assert.match(print.content,/-1,200円/);assert.doesNotMatch(print.content,/20%|discountRate|>800円</);assert.match(print.content,/&lt;test&gt;/)
  assert.equal((await req('/dealer/erp/invoice/'+inv.id,b)).status,404)
  const note=await req('/dealer/erp/shipment/'+ship.id,a)
  assert.match(note.content,/6,000円/);assert.doesNotMatch(note.content,/4,800円|800円|割引/)
  const payment=await action('payment',a,{ organizationId:'salon-a',reference:'BANK-001',paidDate:day,amountYen:2000,note:'一部入金' })
  const settlement=await action('settle',a,{ paymentId:payment.id,invoiceId:inv.id,amountYen:2000 })
  assert.equal((await get('receivables',a)).outstanding,3280)
  await denied('settle',a,{ paymentId:payment.id,invoiceId:inv.id,amountYen:1 },409)
  await denied('invoice-void',a,{ invoiceId:inv.id,reason:'no' },409)
  await denied('payment-void',a,{ paymentId:payment.id,reason:'no' },409)
  const po=await action('purchase',a,{ supplier:'メーカー A',expectedDate:day,lines:[{ productId:'product-a',quantity:4,unitCost:400 }] })
  const poLine=(await get('purchases',a)).rows[0].lines[0]
  await action('receive',a,{ purchaseId:po.id,lineId:poLine.id,quantity:4,locationId:wh.locationId })
  await denied('receive',a,{ purchaseId:po.id,lineId:poLine.id,quantity:1,locationId:wh.locationId },409)
  await action('reserve',staff,{ orderId:'order-ten',lineId:'order-ten-line',locationId:wh.locationId,quantity:4 })
  const ship2=await action('ship',staff,{ orderId:'order-ten' })
  await action('shipment-reverse',staff,{ shipmentId:ship2.id,reason:'積み直し' })
  assert.equal((await get('inventory',a)).rows[0].onHand,4)
  await action('reserve',staff,{ orderId:'order-ten',lineId:'order-ten-line',locationId:wh.locationId,quantity:4 })
  const ship3=await action('ship',staff,{ orderId:'order-ten' })
  await action('deliver',staff,{ shipmentId:ship3.id })
  d=await get('order?id=order-ten',a);assert.equal(d.order.status,'DELIVERED');assert.equal(d.lines[0].delivered,10)
  await action('return',staff,{ shipmentId:ship.id,lineId:d.shipments.find(sh => sh.id===ship.id).lines[0].id,quantity:2,restock:true,reason:'返品受付' })
  assert.equal((await get('inventory',a)).rows[0].onHand,2)
  assert.equal((await get('report?month='+month,a)).summary.actualYen,6400)
  assert.equal((await get('receivables',a)).unbilled[0].amount,1600)
  await action('invoice',a,{ organizationId:'salon-a',closingDate:day,dueDate:day })
  assert.equal((await get('receivables',a)).outstanding,5040)
  await action('settlement-undo',a,{ settlementId:settlement.id,reason:'照合訂正' })
  assert.equal((await get('receivables',a)).outstanding,7040)
  await denied('settlement-undo',a,{ settlementId:settlement.id,reason:'duplicate' },409)
  await action('payment-void',a,{ paymentId:payment.id,reason:'銀行明細で再取込' })
  const bankCsv=`取引番号,サロンコード,入金日,金額,摘要\r\nBANK-002,TEST-A,${day},7040,"テスト,入金"`
  assert.equal((await action('payment-import',a,{ csv:bankCsv })).imported,1)
  assert.equal((await action('payment-import',a,{ csv:bankCsv })).skipped,1)
  await denied('payment-import',a,{ csv:bankCsv.replace('7040','7041') },409)
  await denied('payment-import',a,{ csv:bankCsv+'\r\nBANK-003,INVALID,'+day+',10,no' },400)
  await denied('payment-import',a,{ csv:bankCsv.replace('BANK-002','BANK-ROLLBACK')+'\r\nBANK-003,INVALID,'+day+',10,no' },400)
  assert.equal((await sql('SELECT COUNT(*)::int AS n FROM "DealerErpPayment" WHERE "reference"=\'BANK-ROLLBACK\''))[0].n,0)
  const incoming=(await get('payments',a)).rows.find(p => p.reference==='BANK-002')
  for (const i of (await get('receivables',a)).rows) await action('settle',a,{ paymentId:incoming.id,invoiceId:i.id,amountYen:i.totalYen })
  assert.equal((await get('receivables',a)).outstanding,0)
  await action('return',staff,{ shipmentId:ship3.id,lineId:d.shipments.find(sh => sh.id===ship3.id).lines[0].id,quantity:1,restock:false,reason:'破損返品' })
  const credit=await action('invoice',a,{ organizationId:'salon-a',closingDate:day,dueDate:day })
  const refund=await action('payment',a,{ organizationId:'salon-a',reference:'REFUND-1',paidDate:day,amountYen:-880,note:'返品返金' })
  await action('settle',a,{ paymentId:refund.id,invoiceId:credit.id,amountYen:-880 })
  assert.equal((await get('receivables',a)).outstanding,0)
  await action('order-edit',a,{ orderId:'order-other',lineId:'order-other-line',quantity:3,unitPrice:750,kind:'EDIT',reason:'数量訂正' })
  await action('reserve',a,{ orderId:'order-other',lineId:'order-other-line',locationId:wh.locationId,quantity:2 })
  await action('order-edit',a,{ orderId:'order-other',kind:'CANCEL',reason:'未出荷取消' })
  assert.equal((await get('order?id=order-other',a)).order.status,'CANCELLED')
  assert.equal((await get('inventory',a)).rows[0].reserved,0)
  await action('stock',a,{ ...receive,kind:'TRANSFER',quantity:1,destinationId:wh2.locationId })
  assert.equal((await get('inventory',a)).rows.reduce((n,r)=>n+r.onHand,0),2)
  await action('branch-goal',a,{ branchId:branch.id,month,salesTargetYen:10000,acquisitionTarget:3 })
  await action('terms',a,{ organizationId:'salon-a',paymentMonths:2,paymentDay:15,note:'銀行振込' })
  const activity={ memberId:employee.id,organizationId:'salon-a',kind:'VISIT',title:'月次訪問',startsAt:day+'T10:00:00+09:00',endsAt:day+'T11:00:00+09:00',visibility:'BRANCH',status:'PLANNED',note:'提案',result:'' }
  const act=await action('activity',staff,activity)
  assert.equal((await get('activities?month='+month,staff)).rows[0].startsAt,day+'T01:00:00.000Z')
  await action('activity',staff,{ ...activity,id:act.id,version:1,status:'DONE',result:'新商品をご提案' })
  await denied('activity',staff,{ ...activity,id:act.id,version:1 },409)
  await denied('activity',staff,{ ...activity,memberId:opts.viewer.memberId },403)
  const internal=await action('thread',staff,{ subject:'社内連絡',memberIds:[opts.viewer.memberId],body:'確認をお願いします' })
  const salonThread=await action('thread',staff,{ organizationId:'salon-a',orderId:'order-ten',subject:'納品について',body:'分納分を発送しました。' })
  assert.equal((await get('threads',a)).total,2)
  await denied('message',b,{ threadId:internal.id,body:'foreign' },404)
  const salonHeaders={ 'x-fixture-salon':'1' }
  const salonThreads=await ok('/api/admin/wholesale/erp/threads?dealer=dealer-a','',undefined,salonHeaders)
  assert.equal(salonThreads.total,1);assert.equal(salonThreads.rows[0].unread,1)
  const reply=await ok('/api/admin/wholesale/erp/message?dealer=dealer-a','',{ key:crypto.randomUUID(),threadId:salonThread.id,body:'承知しました。' },salonHeaders)
  assert.ok(reply.id)
  assert.equal((await req('/api/admin/wholesale/erp/messages?dealer=dealer-a&thread='+internal.id,'',undefined,salonHeaders)).status,404)
  const msg=(await get('messages?thread='+salonThread.id,staff)).rows
  assert.equal(msg.length,2)
  await action('read',staff,{ threadId:salonThread.id,messageId:msg.at(-1).id })
  assert.equal((await get('threads',staff)).rows.find(t => t.id===salonThread.id).unread,0)
  assert.equal((await req('/api/dealer/erp/stock',a,{ ...receive,key:crypto.randomUUID() },{ Origin:'https://evil.example' })).status,403)
  assert.equal((await req('/api/dealer/erp/options')).status,401)
  for (const page of ['operations','inventory','fulfillment','receivables','activities','messages']) assert.equal((await req('/dealer/'+page,a)).status,200,page)
  for (const route of ['options','inventory','history','products','orders','purchases','receivables','payments','activities?month='+month,'threads','dashboard?month='+month,'report?month='+month]) assert.equal((await req('/api/dealer/erp/'+route,a)).status,200,route)
  assert.equal((await get('dashboard?month='+month,b)).summary.actualYen,0)
  const raceWarehouse=await action('warehouse',a,{ name:'同時操作検証',location:'R-1' })
  await action('stock',a,{ ...receive,locationId:raceWarehouse.locationId })
  await makeOrder('race-a','salon-a',4);await makeOrder('race-b','salon-a',4)
  const races=await Promise.all(['race-a','race-b'].map(orderId => req('/api/dealer/erp/reserve',staff,{ key:crypto.randomUUID(),orderId,lineId:orderId+'-line',quantity:4,locationId:raceWarehouse.locationId })))
  assert.deepEqual(races.map(r=>r.status).sort(),[200,409],'Concurrent reservations cannot oversell')
  assert.equal((await get('inventory?location='+raceWarehouse.locationId,a)).rows[0].reserved,4)
  const extraReturn=await action('return',staff,{ shipmentId:ship3.id,lineId:d.shipments.find(sh=>sh.id===ship3.id).lines[0].id,quantity:1,restock:true,reason:'未請求返品' })
  assert.ok(extraReturn.id)
  const voidable=await action('invoice',a,{ organizationId:'salon-a',closingDate:day,dueDate:day })
  await action('invoice-void',a,{ invoiceId:voidable.id,reason:'締日訂正' })
  assert.equal((await get('receivables',a)).unbilled[0].amount,-800)
  assert.equal((await get('unread',staff)).unread,0)
  console.log('PASS: receipt/reservation/partial shipment/delivery/return, invoicing/partial payments/reversals/refunds, CSV retry, permissions, reporting, activities, messages')
  if (process.env.KEEP_FIXTURE==='1') {
    console.log('ERP fixture ready at '+base+' (isolated schema '+schema+')')
    await new Promise(resolve => { process.once('SIGTERM',resolve);process.once('SIGINT',resolve) })
  }
} finally {
  await new Promise(resolve => server.close(resolve));await db.$disconnect()
  await bootstrap.$executeRawUnsafe(`DROP SCHEMA "${schema}" CASCADE`);await bootstrap.$disconnect()
}
