import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.env.LIEN_RUNTIME_ROOT || '/app'
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8')
const server = read('server.js')
const commercial = read('commercial-admin-v101.js')
const customer = read('customer-experience-v508.js')
const customerStandalone = read('customer-experience-v503.js')
const productInsights = read('public/product-insights-v515.js')
const layout = read('.next/static/chunks/app/layout-runtime-v516-release5.js')
const customerLayout = read('.next/static/chunks/app/layout-d1470003e928b0b1.customertabs-v503.ui-transition-v516-release5.js')
const css = read('.next/static/css/51ded9af5ca8c344.customer-native-v82.customer-shell-v88.customer-layout-v92.navigation-v84.sidebar-shift-v87.admin-theme-first-paint-v153.ui-transition-v516-release6.css')
const manifest = read('.next/app-build-manifest.json')
const customerManifest = read('.next/server/app/u/login/page_client-reference-manifest.js')
const script = read('public/ui-transition-v516.js')
const style = read('public/ui-transition-v516.css')

assert.match(server, /X-Lien-Ui-Transition-Consistency', 'v516'/)
assert.match(server, /customer-experience-v508\.js\?v=516-release3/)
assert.match(server, /customer-experience-v503\.js\?v=516-release7/)
assert.doesNotMatch(server, /customer-experience-v503\.js\?v=503/)
assert.match(server, /data-orimia-customer-standalone="v516"/)
assert.match(server, /orimia-customer-transition-v516/)
assert.match(server, /ui-transition-v516\.js\?v=516-release7/)
assert.match(server, /product-insights-v515\.js\?v=516-release3/)
assert.match(commercial, /source: 'admin-commercial-v516'/)
assert.match(customer, /source: 'customer-experience-v516'/)
assert.match(customerStandalone, /source: 'customer-standalone-v516'/)
assert.match(customerStandalone, /if \(routeTimer\) return/)
assert.match(customerStandalone, /window\.setTimeout\(start, 40\)/)
assert.match(productInsights, /source: 'admin-product-insights-v516'/)
assert.match(productInsights, /if \(timer\) return/)

assert.match(layout, /commercial-admin-v136\.js\?v=20260901-516-release3/)
assert.match(layout, /source: 'admin-product-insights-v516'/)
assert.match(layout, /ui-transition-consistency-v516/)
assert.match(layout, /orimiaUiReady/)
assert.match(customerLayout, /ui-transition-consistency-v516/)
assert.match(customerLayout, /orimiaUiReady/)
assert.match(css, /ui-transition-consistency-v516/)
assert.match(css, /html:not\(\[data-orimia-ui-ready="v516"\]\)/)
assert.match(manifest, /layout-runtime-v516-release5\.js/)
assert.doesNotMatch(manifest, /layout-runtime-v515\.js/)
assert.match(customerManifest, /customertabs-v503\.ui-transition-v516-release5\.js/)
assert.doesNotMatch(customerManifest, /customertabs-v503\.js"/)
assert.match(manifest, /admin-theme-first-paint-v153\.ui-transition-v516-release6\.css/)

assert.match(script, /orimiaUiReady/)
assert.match(script, /orimia:ui-runtime-ready/)
assert.match(script, /safety-timeout/)
assert.match(script, /route-max-settle/)
assert.match(script, /readySources/)
assert.match(script, /customer-standalone-v516/)
assert.match(script, /pushState/)
assert.match(script, /popstate/)
assert.match(style, /body > :is\(\.admin-app-shell, \.app\) > \*/)
assert.match(style, /data-orimia-customer-standalone="v516"/)
assert.match(style, /orimia-icon-192\.png\?v=516/)

console.log(JSON.stringify({ release: 'ui-transition-consistency-v516', verified: true }))
