name: Deploy style admin pagination v647

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/deploy-style-admin-pagination-v647.yml
