name: Deploy list pagination performance v628

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-customer-booking-points-v652.yml
    secrets: inherit
